infrastructure/samconfig.toml, infrastructure/template.yaml, step-functions/nino_check.asdl.json
Added nino check step function and updated infrastructure.
Moving clickops spike work to code
- [OJ-1804](https://govukverify.atlassian.net/browse/OJ-1804)
[OJ-1804]: https://govukverify.atlassian.net/browse/OJ-1804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1804: Added state machine and updated infrastructure

integration-tests/tests/aws/nino-check-unhappy.test.ts
Added unhappy path scenario tests to nino-check.
Created a new test file to house the failure scenarios. 
Testing
- [OJ-1825](https://govukverify.atlassian.net/browse/OJ-1825)
[OJ-1825]: https://govukverify.atlassian.net/browse/OJ-1825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1825: Added unhappy path tests

deploy.sh
Removed `./gradlew clean` from `deploy.sh` because this repository is not a Java project thus this command is not needed.
When running deploy.sh it fails because gradle does not exist in the project.
=> BAU: Removed `./gradlew clean` from `deploy.sh`

step-functions/nino_check.asl.json
State  machine ASL
We needed a way to track whether the user failed or passed NINO check
=> Added PASS/FAIL outcome to state machine

.secrets.baseline, infrastructure/private-api.yaml, infrastructure/public-api.yaml, infrastructure/template.yaml, step-functions/nino_issue_credential.asl.json
A new state machine was added and infra updated. 
To generate a VC using step functions
- [OJ-1842](https://govukverify.atlassian.net/browse/OJ-1842)
[OJ-1842]: https://govukverify.atlassian.net/browse/OJ-1842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1842: Added  Issue Credentials State Machine

step-functions/nino_issue_credential.asl.json
State Machine ASL
There were some fields missing and some general clean up was done. 
- [OJ-1842](https://govukverify.atlassian.net/browse/OJ-1842)
[OJ-1842]: https://govukverify.atlassian.net/browse/OJ-1842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1842: Added additional fields to VC and small refactoring

.github/workflows/post-merge-deploy-to-build.yml, .github/workflows/post-merge-deploy-to-dev.yml, infrastructure/template.yaml
Tried and tested changes necessary for the stack to be deployable via the pipelines
- Sam version change was necessary as 1.74.0 didn't accept ??? as a wildcard for permissions
- Code signing, permissions boundaries and function url changes were all necessary to allow the stack to deploy
- Add a manual deploy option to the deploy to dev workflow
- [OJ-1819](https://govukverify.atlassian.net/browse/OJ-1819)
[OJ-1819]: https://govukverify.atlassian.net/browse/OJ-1819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1819 update template to allow deploy by workflow

infrastructure/template.yaml
`template.yaml`
HMRC changed the URL for NINO check
=> BAU: Updated NINO check URL

infrastructure/template.yaml, lambdas/issue-credential/.eslintignore, lambdas/issue-credential/.eslintrc.js, lambdas/issue-credential/jest.config.ts, lambdas/issue-credential/package-lock.json, lambdas/issue-credential/package.json, lambdas/issue-credential/src/time-event.ts, lambdas/issue-credential/src/time-handler.ts, lambdas/issue-credential/tests/time-handler.test.ts, lambdas/issue-credential/tsconfig.json, step-functions/nino_issue_credential.asl.json
A new Lambda added for getting the current time
Step Function's currently do not have a way to get the current time or perform any Math operations.
We need this functionality to calculate the expiry and `nbf` values within the VC. 
- [OJ-1842](https://govukverify.atlassian.net/browse/OJ-1842)
[OJ-1842]: https://govukverify.atlassian.net/browse/OJ-1842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1842: Added Time function for `exp` and `nbf` values

infrastructure/samconfig.toml, infrastructure/template.yaml, step-functions/nino_issue_credential.asl.json
Allow for use of own common stack with state machines
- [OJ-1892](https://govukverify.atlassian.net/browse/OJ-1892)
[OJ-1892]: https://govukverify.atlassian.net/browse/OJ-1892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1892 Common stack name substitution

.secrets.baseline, integration-tests/makefile, integration-tests/tests/mocked/MockConfigFile.json, integration-tests/tests/mocked/step-functions-local.test.ts
Added missing mocked data for state machine tests
Tests were failing
=> BAU: Added missing mocks

step-functions/nino_issue_credential.asl.json
This is a possible work Around the step function local in ability to deal with map
=> BAU: Work Around stepfunction local testing

infrastructure/template.yaml, integration-tests/jest.config-aws.ts, integration-tests/tests/aws/check-session/check-session.test.ts, integration-tests/tests/aws/nino-check/nino-check-happy.test.ts, integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts
Added AWS integration tests for the check-session state machine.
Testing
- [OJ-1921](https://govukverify.atlassian.net/browse/OJ-1921)
[OJ-1921]: https://govukverify.atlassian.net/browse/OJ-1921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1921: AWS tests for check-session state machine

.github/workflows/pre-merge-integration-test.yml, integration-tests/tests/aws/nino-check/nino-check-happy.test.ts
Note: To merge when GH role has been fixed by Tim
Added `pre-merge-integration-test.yml` Github workflow
It was added so that we can run the integration tests pre-merge to ensure that changes do not break the system.
- [OJ-1860](https://govukverify.atlassian.net/browse/OJ-1860)
[OJ-1860]: https://govukverify.atlassian.net/browse/OJ-1860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1860: Added pre-merge-integration-test.yml

.github/workflows/post-merge-deploy-to-dev.yml
`post-merge-deploy-to-dev.yml`
Fixes to make it work
=> BAU: Fixed post-merge-deploy-to-dev.yml

infrastructure/template.yaml
Added permissions boundary for CodeDeploy issue
=> BAU: Added permissions boundary to state machines

infrastructure/template.yaml, lambdas/credential-subject/.eslintignore, lambdas/credential-subject/.eslintrc.js, lambdas/credential-subject/jest.config.ts, lambdas/credential-subject/package-lock.json, lambdas/credential-subject/package.json, lambdas/credential-subject/src/credential-subject-builder.ts, lambdas/credential-subject/src/credential-subject-handler.ts, lambdas/credential-subject/src/user-info-event.ts, lambdas/credential-subject/tests/credential-subject-builder.test.ts, lambdas/credential-subject/tests/credential-subject-handler.test.ts, lambdas/credential-subject/tsconfig.json, step-functions/nino_issue_credential.asl.json
Replaces json-path expression, this is due to expression not capable of handling multiple nameparts
A lambda implementation is therefore needed
Related to Map states don't work with step-function local
- [OJ-1928](https://govukverify.atlassian.net/browse/OJ-1928)
[OJ-1928]: https://govukverify.atlassian.net/browse/OJ-1928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1928: replace credential subject with lambda

infrastructure/samconfig.toml, infrastructure/template.yaml
template.yaml
Specific exports needed for the front end to work 
=> BAU: Added exports to CloudFormation

infrastructure/template.yaml
Getting 403 errors
Need to add VpcConfig
=> BAU: Add VpcConfig

.github/workflows/post-merge-deploy-to-build.yml
=> BAU: Added `sam deploy` to post-merge-deploy-to-build.yml

lambdas/credential-subject/src/credential-subject-handler.ts, lambdas/credential-subject/src/user-info-event.ts, step-functions/nino_issue_credential.asl.json
ASL to pass NINO to Lambda
Lambda to use correct object in event
=> OJ-1966: Fix credential subject handler

infrastructure/public-api.yaml
So we output the JWT instead of JSON when calling /credential/issue
=> OJ-1966: Output JWT value for /credential/issue

infrastructure/public-api.yaml
The VTL previously returned the JWK wrapped in " ", this PR changes that show we only get the JWK back without it being wrapped in "
=> OJ-1966: Fix VTL for /credential/issue

.secrets.baseline, integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts, integration-tests/tests/aws/resources/secret-manager-helper.ts, integration-tests/tests/aws/resources/ssm-param-helper.ts, lambdas/matching/src/matching-handler.ts
added new aws unhappy tests
- [OJ-1978](https://govukverify.atlassian.net/browse/OJ-1978)
[OJ-1978]: https://govukverify.atlassian.net/browse/OJ-1978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1978 added new unhappy tests

integration-tests/tests/mocked/nino-check/MockConfigFile.json, integration-tests/tests/mocked/nino-check/makefile, integration-tests/tests/mocked/nino-check/nino-check-unhappy.test.ts, integration-tests/tests/mocked/nino-check/sfn-container-helper.ts
Added missing mocked test for error scenarios
- [OJ-1989](https://govukverify.atlassian.net/browse/OJ-1989)
[OJ-1989]: https://govukverify.atlassian.net/browse/OJ-1989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1989 added missing mock tests

.github/workflows/post-merge-deploy-to-build.yml, .github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/pre-merge-integration-test.yml, .github/workflows/pre-merge-run-lambda-unit-tests.yml
The github workflows
So we can manually trigger actions, there have been times were we need to run GHAs manually for testing and debugging but we can't at the moment without making a new PR
=> OJ-1990: workflow_dispatch added to GHA

step-functions/nino_issue_credential.asl.json
=> BAU: Run independent tasks in parallel

step-functions/nino_issue_credential.asl.json
Credential Subject payload contains info about the state machine execution
VC payload not correct
=> BAU: fix credentialSubject payload

.github/workflows/post-merge-deploy-to-build.yml, .github/workflows/post-merge-deploy-to-dev.yml
It was previously changed to use `sam` because at the time the dev platform action was not working. This is fixed so changing back.
=> BAU: Changed deploy to dev to use dev platform upload action

.github/workflows/post-merge-deploy-to-build.yml, .github/workflows/post-merge-deploy-to-dev.yml
`post-merge-deploy-to-dev.yml`
`post-merge-deploy-to-build.yml`
When running the state machine, it could not find any of the lambdas.
=> BAU: Re-added `sam build` step

lambdas/matching/src/match-event.ts, lambdas/matching/tests/matching-handler.test.ts
`MatchEvent` and test 
MatchEvent had the wrong structure so it was not accurately testing the matching handler.
=> BAU: Fixed test as matching-event was structured incorrectly

infrastructure/template.yaml
=> BAU: Updated Lambda timeout to 30 seconds

integration-tests/tests/mocked/nino-check/MockConfigFile.json
The response for CheckSession was changed so the mocked response needed updating to match.
=> BAU: Updated `CheckSessionSuccess` and `CheckSessionFailure`

infrastructure/template.yaml
ThrottlingRateLimit: 200
ThrottlingBurstLimit: 400
To meet performance testing requirements.
- [OJ-2015](https://govukverify.atlassian.net/browse/OJ-2015)
[OJ-2015]: https://govukverify.atlassian.net/browse/OJ-2015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1881: Increase rate limits

infrastructure/private-api.yaml
OpenAPI spec for /check endpoint to include a 422 response.
HTTP 422 is the response code that /check will respond with for a retry
- [OJ-2198](https://govukverify.atlassian.net/browse/OJ-2198)
[OJ-2198]: https://govukverify.atlassian.net/browse/OJ-2198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2198: Added 422 response code

infrastructure/template.yaml, integration-tests/tests/aws/check-session/check-session.test.ts, integration-tests/tests/aws/nino-check/nino-check-happy.test.ts, integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts, integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-happy.test.ts, integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-unhappy.test.ts, integration-tests/tests/aws/resources/dynamodb-helper.ts, integration-tests/tests/mocked/nino-check/MockConfigFile.json, integration-tests/tests/mocked/nino-check/nino-check-unhappy.test.ts, lambdas/matching/src/matching-handler.ts, lambdas/matching/tests/matching-handler.test.ts, step-functions/nino_check.asl.json, step-functions/nino_issue_credential.asl.json
Reverts govuk-one-login/ipv-cri-check-hmrc-api#102
=> Revert "OJ-2214: Store HMRC response into database"

infrastructure/template.yaml, integration-tests/tests/aws/check-session/check-session.test.ts, integration-tests/tests/aws/nino-check/nino-check-happy.test.ts, integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts, integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-happy.test.ts, integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-unhappy.test.ts, integration-tests/tests/aws/resources/dynamodb-helper.ts, integration-tests/tests/mocked/nino-check/MockConfigFile.json, integration-tests/tests/mocked/nino-check/nino-check-unhappy.test.ts, lambdas/matching/src/matching-handler.ts, lambdas/matching/tests/matching-handler.test.ts, step-functions/nino_check.asl.json, step-functions/nino_issue_credential.asl.json
Reverts govuk-one-login/ipv-cri-check-hmrc-api#105
=> OJ-2214: Store HMRC response into database""

infrastructure/template.yaml, lambdas/ci-mapping/jest.config.ts, lambdas/ci-mapping/package.json, lambdas/ci-mapping/src/ci-mapping-event.ts, lambdas/ci-mapping/src/ci-mapping-handler.ts, lambdas/ci-mapping/tests/ci-mapping-handler.test.ts, lambdas/ci-mapping/tsconfig.json, package-lock.json
Created a Lambda that parses the CIs and matches an input to the CI. 
- [OJ-2213](https://govukverify.atlassian.net/browse/OJ-2213)
[OJ-2213]: https://govukverify.atlassian.net/browse/OJ-2213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2213: Created Lambda to parse CI Mappings

integration-tests/tests/mocked/nino-check/MockConfigFile.json, integration-tests/tests/mocked/nino-check/makefile, integration-tests/tests/mocked/nino-check/nino-check-unhappy.test.ts, lambdas/matching/src/matching-handler.ts, lambdas/matching/tests/matching-handler.test.ts, step-functions/nino_check.asl.json
OJ-2155 (https://govukverify.atlassian.net/browse/OJ-2155)
made changes to state machine to handle Deceased user and added mocked tests
made changes to state machine and added mocked tests
To handle Deceased user case
[OJ-2232](https://govukverify.atlassian.net/browse/OJ-2232)
[OJ-2218](https://govukverify.atlassian.net/browse/OJ-2218)
[OJ-2232]: https://govukverify.atlassian.net/browse/OJ-2232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-2218]: https://govukverify.atlassian.net/browse/OJ-2218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2155 : made changes to state machine and added mocked tests

integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts
OJ-2232 : created new unhappy test for a deceased user
created new unhappy test for a deceased user for integration testing.
=> OJ-2232 : created new unhappy test for a deceased user

infrastructure/template.yaml, integration-tests/tests/aws/nino-check/nino-check-happy.test.ts, integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts, integration-tests/tests/aws/resources/ssm-param-helper.ts, integration-tests/tests/mocked/nino-check/MockConfigFile.json, integration-tests/tests/mocked/nino-check/makefile, integration-tests/tests/mocked/nino-check/nino-check-unhappy.test.ts, step-functions/nino_check.asl.json
- Updated state machine step to use get parameter for url and user agent
- Made the get parameter for url dynamic based off of client id
- Removed ssm parameter for url as this will be done in terraform
- Added ssm parameter for url if dev environment for integration testing
- Added mocked tests for url parameter with dynamic client id
- Added integration tests for url parameter with dynamic client id
- Refactored integration tests
- New feature to make it easier for new clients to access desired apis
- [OJ-2162](https://govukverify.atlassian.net/browse/OJ-2162)
[OJ-2162]: https://govukverify.atlassian.net/browse/OJ-2162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2162: Update existing get useragent and API URL

integration-tests/tests/aws/nino-check/nino-check-happy.test.ts, integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts
Fixed aws tests as per new E2E Test Strategy
- [OJ-2300](https://govukverify.atlassian.net/browse/OJ-2300)
[OJ-2300]: https://govukverify.atlassian.net/browse/OJ-2300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2300 fixed aws test

infrastructure/template.yaml, lambdas/ssm-parameters/jest.config.ts, lambdas/ssm-parameters/package.json, lambdas/ssm-parameters/src/ssm-parameters-handler.ts, lambdas/ssm-parameters/tests/ssm-parameters-handler.test.ts, lambdas/ssm-parameters/tsconfig.json, package-lock.json, package.json
OJ-2242 :created lambda to cache SSM parameters
created lambda to cache SSM parameters
created mock tests for the ssm-pararmeter system
for test coverage.
https://govukverify.atlassian.net/browse/OJ-2242
=> OJ-2242 : created lambda to cache SSM parameters

infrastructure/template.yaml
- Added event bus for Check HMRC
- Needed custom event bus for sending events from state machines
- [OJ-2332](https://govukverify.atlassian.net/browse/OJ-2332)
[OJ-2332]: https://govukverify.atlassian.net/browse/OJ-2332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2332: Added custom event bus to infrastructure.

infrastructure/template.yaml, integration-tests/tests/mocked/nino-check/MockConfigFile.json, step-functions/nino_check.asl.json
- State machine sends response received event to event bus
- Event rule created for response received event 
- To capture events for TXMA
- [OJ-2334](https://govukverify.atlassian.net/browse/OJ-2334)
[OJ-2334]: https://govukverify.atlassian.net/browse/OJ-2334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2334: Update state machine to dispatch response received event

infrastructure/template.yaml, integration-tests/tests/mocked/nino-check/MockConfigFile.json, step-functions/nino_check.asl.json
- Event Rule Added Request Sent event
- StateMachine updated to publish event
- Refactored template.yaml mapping section to include sources for different environments
- [OJ-2334](https://govukverify.atlassian.net/browse/OJ-2334)
[OJ-2334]: https://govukverify.atlassian.net/browse/OJ-2334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Oj 2335 update statemachine to dispatch request sent event

infrastructure/template.yaml, integration-tests/tests/mocked/nino-issue-credential/MockConfigFile.json, step-functions/nino_issue_credential.asl.json
- Added Event rule for VC issued event
- Updated Issue credential state machine:
- Added permissions to invoke event bus
- Added task to publish event
- [OJ-2336](https://govukverify.atlassian.net/browse/OJ-2336)
[OJ-2336]: https://govukverify.atlassian.net/browse/OJ-2336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Oj 2336 update statemachine to dispatch vc issued event

infrastructure/template.yaml, step-functions/nino_issue_credential.asl.json
- Event rule to capture END events created
- State machine task to publish END event to event bus
- [OJ-2360](https://govukverify.atlassian.net/browse/OJ-2360)
[OJ-2360]: https://govukverify.atlassian.net/browse/OJ-2360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Oj 2360 update statemachine to dispatch end event

infrastructure/template.yaml, integration-tests/tests/mocked/abandon/MockConfigFile.json, step-functions/abandon.asl.json, step-functions/nino_issue_credential.asl.json
- Added abandoned event rule
- Updated state machine to publish abandoned event
- Updated mocked tests
- To track abandoned journeys
- 
- [OJ-2349](https://govukverify.atlassian.net/browse/OJ-2349)
[OJ-2349]: https://govukverify.atlassian.net/browse/OJ-2349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Oj 2349 update statemachine to dispatch abandoned event

infrastructure/public-api.yaml
=> BAU: Fix VTL to return 200

step-functions/nino_issue_credential.asl.json
Endpoint was returning a VC with a 500 status.
=> BAU: Add 200 status to issue credential state machine

infrastructure/template.yaml
Added permission boundary to role
Required for deployment from aws pipelines
=> BUGFIX Added permission boundary to event bridge state machine role

infrastructure/template.yaml
Added and updated cloudwatch alarms for the API Gateway, State Machines and Step functions.
Added Slack (and pager duty in production) notifications of critical alerts
Added slack notifications of warning alerts
To improve and standardise the cloudwatch monitoring and alerting
- [IPS-617](https://govukverify.atlassian.net/browse/IPS-617)
- [IPS-664](https://govukverify.atlassian.net/browse/IPS-664)
- [IPS-671](https://govukverify.atlassian.net/browse/IPS-671)
- [IPS-672](https://govukverify.atlassian.net/browse/IPS-672)
- [IPS-621](https://govukverify.atlassian.net/browse/IPS-621)
- [IPS-622](https://govukverify.atlassian.net/browse/IPS-622)
- [IPS-623](https://govukverify.atlassian.net/browse/IPS-623)
[IPS-617]: https://govukverify.atlassian.net/browse/IPS-617?atlOrigin=eyJpIjoiNWRkNTljNz …
=> Ips 617 apigw and step functions cloudwatch alarms

integration-tests/api-gateway/aws/e2e-retry-path.test.ts
We added the e2e retry test and asserted we received a CI and a validity score of 0
For testing code coverage
- [OJ-2521](https://govukverify.atlassian.net/browse/OJ-2521)
[OJ-2521]: https://govukverify.atlassian.net/browse/OJ-2521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2521 Added e2e retry test

integration-tests/step-functions/aws/nino_issue_credential/nino_issue_credential.test.ts, step-functions/audit_event.asl.json, step-functions/nino_issue_credential.asl.json
see:  https://govukverify.atlassian.net/browse/OJ-2483
Audit name prefix change see https://github.com/govuk-one-login/ipv-cri-pipeline-deployment/pull/182
"IPV_CHECK_HMRC_CRI" to IPV_HMRC_RECORD_CHECK_CRI
The IPV_HMRC_RECORD_CHECK_CRI_VC_ISSUED event should also include:
Added number of attempts, restricted information and validity scores to VC Audit Event
- [OJ-2483](https://govukverify.atlassian.net/browse/OJ-2483)
See VC_ISSUED event below
```
{
"component_id": "https://review-hc.dev.account.gov.uk",
"extensions": {
"evidence": [
{
"failedCheckDetails": [
{
"checkMethod": "data"
}
],
"validityScore": 0,
"strengthScore": 2,
"ci": [
"CI0"
],
"txn": "c39b421f-b0c8-4302-aca4-e7f3af2e5957",
"type": "IdentityCheck",
"attemptNum": 2,
"ciReasons": [
{
"ci": "CI0",
"reason": "some reason for …
```
=> OJ-2483: Attempt no and restricted info in vc issued event

integration-tests/api-gateway/abandon/abandon-happy.test.ts, integration-tests/api-gateway/authorization/authorization-happy.test.ts, integration-tests/api-gateway/check/check-happy.test.ts, integration-tests/api-gateway/e2e/e2e-happy-path.test.ts, integration-tests/api-gateway/e2e/e2e-retry-path.test.ts, integration-tests/api-gateway/env-variables.ts, integration-tests/api-gateway/session/session-happy.test.ts
We removed all of the console logs from the tests and standardised the test names. We also moved our e2e-retry test to the e2e directory and removed the aws directory.
To fit the standards of testing and for code quality purposes
- [OJ-2532](https://govukverify.atlassian.net/browse/OJ-2532)
[OJ-2532]: https://govukverify.atlassian.net/browse/OJ-2532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated test names and removed console logs

README.md
Updated README.md
How we run, tests defined in the package.json file
Better naming required
- [OJ-2532](https://govukverify.atlassian.net/browse/OJ-2532)
[OJ-2532]: https://govukverify.atlassian.net/browse/OJ-2532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2532: Update Readme

infrastructure/template.yaml
see: https://govukverify.atlassian.net/browse/OJ-2501
Follow up PR to https://github.com/govuk-one-login/ipv-cri-check-hmrc-api/pull/223
- [OJ-2420](https://govukverify.atlassian.net/browse/OJ-2420)
[OJ-2420]: https://govukverify.atlassian.net/browse/OJ-2420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2420: Enable Eventbridge in all environments

infrastructure/template.yaml
The last PR didn't work
- [OJ-2420](https://govukverify.atlassian.net/browse/OJ-2420)
[OJ-2420]: https://govukverify.atlassian.net/browse/OJ-2420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2420: change ENABLED to 'ENABLED' in EventBusState

step-functions/audit_event.asl.json
Payload needs some adjustment
```
[
{
"auditEvent": {
"component_id": "https://review-hc.staging.account.gov.uk",
"event_timestamp_ms": 1714670288645,
"event_name": "IPV_HMRC_RECORD_CHECK_CRI_END",
"user": {
"govuk_signin_journey_id": "631d3904-4304-4664-8973-719a17c34b1d",
"user_id": "urn:fdc:gov.uk:2022:1d755be8-dbec-4bbd-941d-b8f503016a8e",
"persistent_session_id": "8c8e999d-e385-4e55-8548-fd31b1fcbeb3",
"session_id": "392daeb0-fd3b-4131-b2e1-c62fd1cb8d94",
"ip_address": "18.169.162.17, 10.0.10.189"
},
"timestamp": 1714670288
}
},
{
"prefix": "IPV_HMRC_RECORD_CHECK_CRI",
"type": "END",
"epochSeconds": { "value": 1714670288 }
},
{
"prefix": "IPV_HMRC_RECORD_CHECK_CRI",
"type": "END",
"epochMilliseconds": { "value": 1714670288645 }
}
]
```
```
{
"component_id": …
```
=> Oj 2420 adjust payload audit event

integration-tests/step-functions/aws/nino-check/nino-check-unhappy.test.ts
This test was doing what it was supposed to, this a quick fix. I was failing on session-check inside
=> BAU: Fixed broken test

infrastructure/template.yaml
Disable alarms in dev environments, to reduce noise in the alerting/warning Slack channels
=> Disable alarms in dev

lambdas/pii-redact/src/pii-redactor.ts, lambdas/pii-redact/tests/redact-pii.test.ts
Added additional regexes for PII
Additional groups needed capturing to redact PII
- [OJ-2319](https://govukverify.atlassian.net/browse/OJ-2319)
[OJ-2319]: https://govukverify.atlassian.net/browse/OJ-2319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2319: Add additional checks to the regexes for PII

lambdas/pii-redact/src/pii-redactor.ts, lambdas/pii-redact/tests/redact-pii.test.ts
Grouped the regex and replacements for readability.
Fixed tests/replacement logic to ensure an exact replacement as previously it was not producing the exact output as the input. Now it is ensured that just the value is censored and extra characters are not removed/added. 
- [OJ-2319](https://govukverify.atlassian.net/browse/OJ-2319)
[OJ-2319]: https://govukverify.atlassian.net/browse/OJ-2319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2319: Refactor pii-redactor.ts for readability + fixes

infrastructure/private-api.yaml, integration-tests/api-gateway/abandon/abandon-happy.test.ts, integration-tests/api-gateway/authorization/authorization-happy.test.ts, integration-tests/api-gateway/check/check-happy.test.ts, integration-tests/api-gateway/endpoints.ts
- Updated api spec for /check and /abandon
- Added API tests for when optional header is included
- Actual functionality of audit event bodies is covered in eventbridge tests
- [OJ-2574](https://govukverify.atlassian.net/browse/OJ-2574)
[OJ-2574]: https://govukverify.atlassian.net/browse/OJ-2574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2574: API gateway tests for txma header

infrastructure/template.yaml
EventBridgeToSqsPolicy has been removed as it's been moved to common-infra now. See PR https://github.com/govuk-one-login/ipv-cri-common-infrastructure/pull/90
SQS queues can only have one policy so the EventBridgeToSqsPolicy was overriding the AuditEventQueuePolicy allowing the TxMA account to read from it in staging
**Before**
**After**
- [OJ-1851](https://govukverify.atlassian.net/browse/OJ-1851)
[OJ-1851]: https://govukverify.atlassian.net/browse/OJ-1851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1851 Remove EventBridgeToSqsPolicy

.github/workflows/deploy-branch.yml, .pre-commit-config.yaml, infrastructure/template.yaml
Added the KmsKeyIdentifier to the event bus because it was failing to encrypt messages for the txma SQS queue causing it to fail.
- [OJ-1851](https://govukverify.atlassian.net/browse/OJ-1851)
[OJ-1851]: https://govukverify.atlassian.net/browse/OJ-1851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-1851: Add KmsKeyIdentifier to Event Bus

integration-tests/eventbridge/nino-check/nino-check-publish.test.ts, integration-tests/eventbridge/nino_issue_credential/nino-issue-credential-publish.test.ts, integration-tests/step-functions/aws/nino_issue_credential/nino_issue_credential.test.ts, integration-tests/step-functions/mocked/audit-event/audit-event.test.ts, integration-tests/step-functions/mocked/nino-check/MockConfigFile.json, integration-tests/step-functions/mocked/nino-issue-credential/MockConfigFile.json, lambdas/matching/src/matching-handler.ts, lambdas/matching/tests/matching-handler.test.ts, step-functions/audit_event.asl.json, step-functions/nino_check.asl.json, step-functions/nino_issue_credential.asl.json
- Retrieved the txn value in the matching lambda when it successfully matches. 
- Modified the logger in the matching lambda to use it's own impl, this is so I could attach the txn as a key. 
- Store txn in the session table.
- Send txn in TxMA audit logs. 
To log the txn value to TxMA
- [OJ-2467](https://govukverify.atlassian.net/browse/OJ-2467)
[OJ-2467]: https://govukverify.atlassian.net/browse/OJ-2467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Oj 2467 hmrc transaction ref

infrastructure/template.yaml
Update the supportManualUrl from confluence to the published URL
As a DI 2nd line support engineer
I want to have the runbook for an alarm close at hand
So that I can quickly understand how to respond
- [OJ-2316](https://govukverify.atlassian.net/browse/OJ-2316)
[OJ-2316]: https://govukverify.atlassian.net/browse/OJ-2316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2316: Update the supportManualUrl to the published URL

infrastructure/template.yaml
- Removed dimension from PutEventAlarm as it did not exist on the metric, now PutEvents Failures to any EventBus will alarm, the only way I could get this to work.
- Refactored conditions on all audit alarms to actually adhere to the alarm description.
- Set Audit alarms TreatMissingData to notBreaching, otherwise it would be strange for the alarm to transition from InsufficientData -> Ok upon 1-3 errors within an hour.
I could not see the EventBusName dimension on the putEventsApproximateFailedCount metric, so I have removed to keep the alarm for all PutEvents to any EventBus.
The `TreatMissingData: missing` behaved differently then it looks like was thought with how the alarms are configured. There is a good description on this …
=> OJ-2609: Audit alarms review

infrastructure/template.yaml
Reverts govuk-one-login/ipv-cri-check-hmrc-api#324
=> Revert "OJ-2609: Removing PutEvent alarm (Will be reverted)"

lambdas/pii-redact/src/pii-redact-handler.ts, lambdas/pii-redact/src/pii-redactor.ts, lambdas/pii-redact/src/regex/address.ts, lambdas/pii-redact/src/regex/date-of-birth.ts, lambdas/pii-redact/src/regex/ip-address.ts, lambdas/pii-redact/src/regex/name-pattern.ts, lambdas/pii-redact/src/regex/personal-number.ts, lambdas/pii-redact/src/regex/uncategorised-patterns.ts, lambdas/pii-redact/tests/pii-redact-handler.test.ts, lambdas/pii-redact/tests/pii-redactor.test.ts
Format the JSON that gets sent to the pii redacted log group.
Screenshots to illustrate the example 
**Before**
**After**
=> Fix output format

integration-tests/step-functions/aws/nino-check/nino-check-happy.test.ts
Updated test data to match imposter stub changes in [this PR](https://github.com/govuk-one-login/ipv-third-party-stubs/pull/237)
Imposter stub has been updated to use NINo to trigger a NINo failure scenarion
- [OJ-2727](https://govukverify.atlassian.net/browse/OJ-2727)
[OJ-2727]: https://govukverify.atlassian.net/browse/OJ-2727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2727: Update test data to match stub changes

integration-tests/api-gateway/abandon/abandon-unhappy.test.ts, integration-tests/api-gateway/authorization/authorization-unhappy.test.ts, integration-tests/api-gateway/check/check-unhappy.test.ts, integration-tests/api-gateway/endpoints.ts, integration-tests/api-gateway/session/session-unhappy.test.ts
Update api-gateway tests to include validation scenarios in preparation for pre-prod and prod testing
To increase test coverage for integration tests.
- [OJ-2463](https://govukverify.atlassian.net/browse/OJ-2463)
[OJ-2463]: https://govukverify.atlassian.net/browse/OJ-2463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add unhappy tests for api endpoints

infrastructure/template.yaml
Modified alarms for PagerDuty setup
- [OJ-2616](https://govukverify.atlassian.net/browse/OJ-2616)
[OJ-2616]: https://govukverify.atlassian.net/browse/OJ-2616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2616 - Modified alarms for PagerDuty setup

package-lock.json, package.json
Remove esbuild-jest
Unused dependency that has a transitive dependency with a security vulnerability https://github.com/govuk-one-login/ipv-cri-check-hmrc-api/security/dependabot/13
=> Remove esbuild-jest

lambdas/matching/src/matching-handler.ts, lambdas/matching/src/name-part.ts, lambdas/matching/tests/matching-handler.test.ts, step-functions/nino_check.asl.json
With the introduction of a middle name added means that the index values that are being checked in "User Exists?" is no longer correct. Previously we check if index 0 and index 1 were present. But now, index 1 could conditionally be middle name. The MatchingHandler handles this logic now so this PR updates the User Exists check to ensure the entire names structure is present.
=> BAU: Update "User Exists"? condition to check for the entire names object instead of doing it individually by index

infrastructure/template.yaml
Fixing typo in the substitution name
=> OJ-2798: Fix typo

integration-tests/package.json, package-lock.json
Remove unsued depencency aws-testing-library
Resolve https://github.com/govuk-one-login/ipv-cri-check-hmrc-api/security/dependabot/10
- [OJ-2892](https://govukverify.atlassian.net/browse/OJ-2892)
[OJ-2892]: https://govukverify.atlassian.net/browse/OJ-2892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2892: BAU vuln fix

infrastructure/template.yaml
- Fix cfn lint error
- Pinned sam cli version
Linting is failing with most recent version of sam cli releease 2 days ago
Before
```
[[W8003: Fn::Equals will always return true or false] ([0, 1] will always return False) matched 73]
Error: Linting failed. At least one linting rule was matched to the provided template.
```
After 
```
/Users/ccooling/projects/gds/ipv-cri-check-hmrc-api/infrastructure/template.yaml is a valid SAM Template
```
=> Fix cfn lint error

package-lock.json
Ran `npm audit fix`
Fix https://github.com/govuk-one-login/ipv-cri-check-hmrc-api/security/dependabot/35
- [OJ-3330](https://govukverify.atlassian.net/browse/OJ-3330)
[OJ-3330]: https://govukverify.atlassian.net/browse/OJ-3330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-3330: Audit fix

integration-tests/api-gateway/jwks-endpoint/jwks-endpoint.test.ts
Update expected alg
Keys created by jwks endoint have updated alg
- [OJ-3400](https://govukverify.atlassian.net/browse/OJ-3400)
[OJ-3400]: https://govukverify.atlassian.net/browse/OJ-3400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-3400: Update expected alg
