govuk-one-login/ipv-cri-check-hmrc-api

- .pre-commit-config.yaml
Exclude package-lock.json from pre-commit large file checks
> BAU: Exclude package-lock from pre-commit

- step-functions/nino_check.asl.json
The "Invoke Check Session" uses the StartSyncExecution instead of a Lambda invoke.
We previously used a Lambda because invoking a state machine from an express state machine was not supported. This has since changed so we no longer need to use a Lambda to invoke an express state machine from another express state machine.
> BAU: Changed "Invoke Check Session" to use StartSyncExecution

- infrastructure/template.yaml
The permission was missing and it's needed for the StartSyncExecution to work.
> BAU: Added `StartSyncExecution` Permission to `NinoCheckStateMachine`

- infrastructure/template.yaml
To call the Imposter URL, AWS needs a stage name which is currently defined as the Imposter function name.
> BAU: Add stage name to Imposter URL

- .secrets.baseline
- infrastructure/public-api.yaml
- integration-tests/tests/aws/nino-check/nino-check-happy.test.ts
- integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts
- integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-happy.test.ts
- integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-unhappy.test.ts
- step-functions/nino_issue_credential.asl.json
`public-api.yaml`: To respond with 400s and 500s on error
`nino_issue_credential.asl.json`: Updated so the placeholder "validate bearer token" has been replaced with actual bearer token checking.
Screenshot:
Before:
After:
> Bau validate bearer token

- .eslintrc.js
- .github/workflows/pre-merge-run-lambda-unit-tests.yml
- .prettierrc.json
- .secrets.baseline
- infrastructure/template.yaml
- integration-tests/package-lock.json
- integration-tests/package.json
- integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts
- integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-happy.test.ts
- integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-unhappy.test.ts
- integration-tests/tests/aws/resources/secret-manager-helper.ts
- jest.config.base.ts
- jest.config.ts
- lambdas/credential-subject/package.json
- lambdas/issue-credential/package.json
- lambdas/jwt-signer/jest.config.ts
- lambdas/jwt-signer/package.json
- lambdas/jwt-signer/src/jwt-signer-handler.ts
- lambdas/jwt-signer/src/signage-type.ts
- lambdas/jwt-signer/src/signer-payload.ts
- lambdas/jwt-signer/src/test-data.ts
- lambdas/jwt-signer/tests/jwt-signer-handler.test.ts
- lambdas/jwt-signer/tsconfig.json
- lambdas/matching/package.json
- package-lock.json
- package.json
- sonar-project.properties
- tsconfig.eslint.json
This is part of https://govukverify.atlassian.net/browse/OJ-2045
For issue credential statemachine, it would be nice to be able to verify the signature that is used to sign the VC. This is what the PR works towards.
**PART ONE:** JwtSignerHandler and associated Tests, JwtSignerHandler was generated using `cri-templates` repo. So changes have been made due to files introduce by templating scaffold to align better with future shape of code generation.
In order to be able to test signature verification, the signing of the vc will now be done a new lambda `JwtSignerHandler`
verification on signature produced via aws kms stepfunction integration was not in the JOSE format. Attempts to use a specific lambda that converts to the binary format of the DER produced by the KMS integration failed. …
> Oj-2045 jwt signature verification

- .secrets.baseline
- lambdas/jwt-signer/src/test-data.ts
- lambdas/jwt-signer/tests/jwt-signer-handler.test.ts
- package-lock.json
**OJ-2045: Simplify JWT signer tests**
- Move common setup code to the top of the test file
  Set up the `KMSClient` mock at the top
  Spy once on the method we want to mock so the spy doesn't need to be created in each test
  Improve readability as it's easier to understand `expect(kmsClient.send)....` than `expect(spy)...`
- Refactor and reduce the amount of code
  Remove unnecessary type assertions
  Inline one-time use constants that are not large enough to be defined separately
- Add newlines and make the tests easier to read, understand the logic and maintain
Reduce nesting of tests
- Use the javascript `String.substring` and `Array.fill` functions to replace the more complex logic
**BAU: Exclude test secrets from secrets check**
Exclude specific known non-secrets rather than having …
> OJ-2045: Simplify JWT signer tests

- infrastructure/template.yaml
Integration does not use Imposter Stub so this has been changed so that it uses the HMRC sandbox URL instead
> BAU: Change integration to use sandbox URL

- step-functions/check_session.asl.json
Restrict output to required data using ResultSelector
Unecessary data is passed across states
Makes outputs more obvious,  and less bloated
Now 
```
{
"sessionId": "123456789",
"currentTime": {
"value": "1700829076"
},
"sessionQuery": {
"count": 1,
"items": [
{
"expiryDate": {
"N": "0"
},
"sessionId": {
"S": "123456789"
}
}
]
}
}
```
Before 
```
{
"sessionId": "123456789",
"currentTime": {
"ExecutedVersion": "$LATEST",
"Payload": "1700581384",
"SdkHttpMetadata": {
"AllHttpHeaders": {
"X-Amz-Executed-Version": [
"$LATEST"
],
"x-amzn-Remapped-Content-Length": [
"0"
],
"Connection": [
"keep-alive"
],
"x-amzn-RequestId": [
"1a2f46e5-1d43-42db-b722-a9932d6f1480"
],
"Content-Length": [
"12"
],
"Date": [
"Tue, 21 Nov 2023 15:43:04 GMT"
],
"X-Amzn-Trace-Id": [ …
```
> BAU: use result selector

- step-functions/nino_check.asl.json
Restrict output to required data using ResultSelector
Unecessary data is passed across states
before:
```
{
"userDetails": {
"firstName": "Jim",
"lastName": "Ferguson",
"dob": "xxxx-xx-xx"
},
"oAuthToken": "goodToken",
"apiURL": "https://xxxxx.execute-api.eu-west-2.amazonaws.com/dev/individuals/authentication/authenticator/api/match",
"userAgent": "govuk-one-login",
"sessionId": "123456789",
"nino": "AA000003D",
"hmrc_response": {
"ExecutedVersion": "$LATEST",
"Payload": {
"firstName": "Jim",
"lastName": "Ferguson",
"dateOfBirth": "xxxx-xx-xx",
"nino": "AA000003D"
},
"SdkHttpMetadata": {
"AllHttpHeaders": {
"X-Amz-Executed-Version": [
"$LATEST"
],
"x-amzn-Remapped-Content-Length": [
"0"
],
"Connection": [
"keep-alive"
],
"x-amzn-RequestId": [
"24515f78-0006-489d-8c6b-ee7e61dcbd75"
], …
```
> BAU: Use ResultSelector

- .github/workflows/check-pr.yml
- .github/workflows/clean-up-deployments.yml
- .github/workflows/delete-deployment.yml
- .github/workflows/deploy-branch.yml
- .github/workflows/scan-repo.yml
- deploy.sh
- package.json
Update the dev deployment script
- Apply formatting
- Add tags to deployed stacks
- Use an S3 prefix
- Use the region from the environment, or use the default value if it's not set
- Set the -u flag to fail if any variable is missing a value
- Remove unused and invalid parameter overrides
- Validate the SAM template before building it
Use the latest shared GitHub Actions
- Pull in the fix to the SonarCloud permissions issue
> OJ-1960: Update dev deployment script from the templates repo & fix SonarCloud permissions issue

- .github/workflows/clean-up-deployments.yml
- README.md
- deploy.sh
- infrastructure/public-api.yaml
- infrastructure/template.yaml
**Remove private API duplication from the SAM template**
The private and "dev only" APIs are the same except for two properties - use the dev env condition to set the correct values for those properties instead of duplicating the whole API block and using complex logic to select the correct ARN for the output.
- Delete the "dev only" API as it is just the private API in dev mode (no auth and type is regional instead of private)
- Use the IsDevEnvironment condition, and remove IsNotDevEnvironment since it's not necessary
- Set the correct OpenAPI version in the resources - we use 3.0.1 (not 3.1.0, which is not supported by CF)
- Use the `GetAtt` function to get the ARNs of the log groups
- Use consistent group name prefixes for different services
---
Allow custom common stack name when …
> BAU: Remove private API duplication in the SAM template

- .github/workflows/check-pr.yml
- .github/workflows/clean-up-deployments.yml
- .github/workflows/delete-deployment.yml
- .github/workflows/deploy-branch.yml
- .github/workflows/run-unit-tests.yml
- .github/workflows/scan-repo.yml
- deploy.sh
- integration-tests/jest.config.ci.ts
- integration-tests/package.json
- jest.config.base.ts
- jest.config.ts
- lambdas/credential-subject/jest.config.ts
- lambdas/credential-subject/package.json
- lambdas/issue-credential/jest.config.ts
- lambdas/issue-credential/package.json
- lambdas/jwt-signer/jest.config.ts
- lambdas/jwt-signer/package.json
- lambdas/matching/jest.config.ts
- lambdas/matching/package.json
- package.json
- Remove unused SAM parameter from the Preview workflow
- Use the summary reporter for GitHub Actions
- Only archive the coverage report file for SonarCloud
- Use the latest shared GitHub Actions
Use the SAM build cache instead of the artifact to improve performance.
**Update the deployment script to enable easy deployment to dev**
- Derive stack name from the user's name and the CRI name if the name is not provided to the script
- Add a deploy script to the package.json files so a stack can be quickly deployed from anywhere in the repo by simply running `npm run deploy`
> BAU: Update deployment workflows and script

- integration-tests/package-lock.json
- integration-tests/package.json
- integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-happy.test.ts
- integration-tests/tests/aws/resources/kms-helper.ts
- package-lock.json
The second PART to https://github.com/govuk-one-login/ipv-cri-check-hmrc-api/pull/70
Which ties the jwt-signer-handler to the step function
What changed
KMS signing used to be done using step function integration, this was inadequate for two reasons:
The format of the signature is DER and ideally should be JOSE format
If the VC payload becomes heavy enough, then the signed message sha256 hashed
The jwt-signer-handler does the above two jobs
Why did it change
Verification of the signature in typescript, was difficult moving the functionality into typescript allowed better testabililty
> OJ-2045: signature verification integration test

- deploy.sh
- integration-tests/tests/aws/jest.config.ts
- integration-tests/tests/mocked/jest.config.ts
- The `whoami` alias might not be set up by default by the CLI so use the full command instead
- Fix jest config error
Fix the error `Can't find a root directory while resolving a config file path` when running an individual test rather than the whole suite.
> BAU: Minor fixes to jest config and deployment script

- integration-tests/tests/mocked/nino-check/MockConfigFile.json
- integration-tests/tests/mocked/nino-check/nino-check-unhappy.test.ts
- lambdas/matching/src/matching-handler.ts
- lambdas/matching/tests/matching-handler.test.ts
- step-functions/nino_check.asl.json
matching-handler.ts and state machine to accompany changes.
Renamed some of the states to be correct e.g. "Query Session" is now "Query Person Identity Table". These are so the states are clearly and accurately describing what they are doing. 
We need the status code back from HMRC as part of the CRI functionality. 
- [OJ-2215](https://govukverify.atlassian.net/browse/OJ-2215)
[OJ-2215]: https://govukverify.atlassian.net/browse/OJ-2215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2215: Matching Handler to return status code and body

- infrastructure/template.yaml
- integration-tests/tests/aws/check-session/check-session.test.ts
- integration-tests/tests/aws/nino-check/nino-check-happy.test.ts
- integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts
- integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-happy.test.ts
- integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-unhappy.test.ts
- integration-tests/tests/aws/resources/dynamodb-helper.ts
- integration-tests/tests/mocked/nino-check/MockConfigFile.json
- integration-tests/tests/mocked/nino-check/nino-check-unhappy.test.ts
- lambdas/matching/src/matching-handler.ts
- lambdas/matching/tests/matching-handler.test.ts
- step-functions/nino_check.asl.json
- step-functions/nino_issue_credential.asl.json
* Updated state machine to save an attempt when they are either successful or if the match fails. The state machine will no longer count any failure (i.e. internal errors) as an attempt.
* Removed unable to save user state as errors are already captured by default. 
* Updated nino-attempts table to include status and text
* Updated attempt checking to be based on number of records
* Updated match-handler.ts to return the status code as a String to allow DynamoDB to save this
* Updated HMRC error block to capture errors correctly in state machine
* Changed tests to use different mock data between them. 
- [OJ-2214](https://govukverify.atlassian.net/browse/OJ-2214)
[OJ-2214]: https://govukverify.atlassian.net/browse/OJ-2214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …
> OJ-2214: Store HMRC response into database

- infrastructure/template.yaml
- integration-tests/tests/aws/nino-check/nino-check-happy.test.ts
- integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts
- integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-happy.test.ts
- integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-unhappy.test.ts
- step-functions/nino_check.asl.json
- step-functions/nino_issue_credential.asl.json
Removed NinoAttemptsTable from CF and updated tests to use the new UserAttemptsTable
It was renamed to UserAttemptsTable
> BAU: Removed unused NinoAttemptsTable

- infrastructure/private-api.yaml
- integration-tests/tests/aws/nino-check/nino-check-happy.test.ts
- integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts
- integration-tests/tests/mocked/nino-check/nino-check-happy.test.ts
- integration-tests/tests/mocked/nino-check/nino-check-unhappy.test.ts
- step-functions/nino_check.asl.json
State machine has been changed to respond with specified `httpStatus` codes.
VTL in the private-api has been updated to use the `httpStatus` output of the state machine
Tests have been updated to reflect these changes
- [OJ-2156](https://govukverify.atlassian.net/browse/OJ-2156)
[OJ-2156]: https://govukverify.atlassian.net/browse/OJ-2156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2156: Respond with correct status codes

- infrastructure/template.yaml
- integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-unhappy.test.ts
- lambdas/ci-mapping/src/ci-mapping-event-validator.ts
- lambdas/ci-mapping/src/ci-mapping-event.ts
- lambdas/ci-mapping/src/ci-mapping-handler.ts
- lambdas/ci-mapping/src/utils/ci-mapping-util.ts
- lambdas/ci-mapping/tests/ci-mapping-event-validator.test.ts
- lambdas/ci-mapping/tests/ci-mapping-handler.test.ts
- lambdas/ci-mapping/tests/utils/ci-mapping-utils.test.ts
- step-functions/nino_issue_credential.asl.json
* State Machine uses the ci-mapping-function to generate CI codes
So that we no longer have the dummy CI in the VC but instead use a real one that uses the HMRC response.
- [OJ-2113](https://govukverify.atlassian.net/browse/OJ-2113)
[OJ-2113]: https://govukverify.atlassian.net/browse/OJ-2113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2113: Updated state machine to use CI from mapping

- infrastructure/template.yaml
- integration-tests/tests/aws/check-session/check-session.test.ts
- integration-tests/tests/aws/nino-check/nino-check-happy.test.ts
- integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts
- integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-happy.test.ts
- integration-tests/tests/aws/nino_issue_credential/nino_issue_credential-unhappy.test.ts
- integration-tests/tests/mocked/check-session/MockConfigFile.json
- integration-tests/tests/mocked/check-session/check-session.test.ts
- step-functions/check_session.asl.json
The check-session state machine's .ASL file has been updated to return the clientId from the session table. 
As part of this PR, the name attribute has been removed from the state machine definition within the template.yaml. This is because we are running into a name length limit so by removing this attribute AWS will manage this for us. 
The nino-check state machine requires a clientId.
The check-session state machine queries the session table which contains the clientId so to avoid re-querying the session table again, we are going to return it in the check-session state machine.
- [OJ-2161](https://govukverify.atlassian.net/browse/OJ-2161)
[OJ-2161]: https://govukverify.atlassian.net/browse/OJ-2161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
> OJ-2161: Update check-session state machine to return clientId

- deploy.sh
- infrastructure/public-api.yaml
- infrastructure/template.yaml
Added condition into the private-api, so that a developer can spin up a stack in which it is possible to lunch the check-front end CRI on localhost to work in conjunction with a ipv-stub also run on a separate port locally on the dev machine
see: https://govukverify.atlassian.net/wiki/spaces/DID/pages/3206512675/Running+CRI+s+locally
Added `localdev` to template and deploy.sh
DEV has been changed to align closer to the other environments, it used to be used by developer in conjunction with a stack they have deployed however it is also a legimate environment on the pipeline. Creating this new environment `localdev` provides a better separation of intent, where `localdev` is used with the deploy.sh script
- [IPS-497](https://govukverify.atlassian.net/browse/IPS-497)
[IPS-497]: …
> IPS-497: check cri for local dev stack

- integration-tests/tests/aws/nino-check/nino-check-happy.test.ts
- integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts
The bad nino value in some of the tests.
The Imposter scenarios had some changes, so these tests needed to be updated to match so that they continue working.
> BAU: Updated bad NINO value within the tests to match updated Imposter scenario

- .github/dependabot.yml
- Added github actions to the dependabot config
- Dependabot will raise automatic PRs to increase the versions of repos used in the github actions workflows
- Keeps code up to data and fixes errors
- [IPS-527](https://govukverify.atlassian.net/browse/IPS-527)
[IPS-527]: https://govukverify.atlassian.net/browse/IPS-527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-527: Add dependabot config

- infrastructure/private-api.yaml
- infrastructure/template.yaml
- integration-tests/tests/aws/abandon/abandon.test.ts
- integration-tests/tests/aws/resources/dynamodb-helper.ts
- integration-tests/tests/mocked/abandon/MockConfigFile.json
- integration-tests/tests/mocked/abandon/abandon.test.ts
- integration-tests/tests/mocked/abandon/docker-compose.yaml
- integration-tests/tests/mocked/abandon/makefile
- integration-tests/tests/mocked/abandon/sfn-constants.ts
- integration-tests/tests/mocked/abandon/sfn-container-helper.ts
- integration-tests/tests/mocked/check-session/sfn-container-helper.ts
- step-functions/abandon.asl.json
Added the /abandon endpoint which when invoked removes the authorizationCode from the session .
This endpoint returns a HTTP 200 with empty body on success.
HTTP 400 if the sessionId is invalid or HTTP 500 on internal errors. 
**Screenshot**
- [OJ-2345](https://govukverify.atlassian.net/browse/OJ-2345)
[OJ-2345]: https://govukverify.atlassian.net/browse/OJ-2345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2345: Create /abandon endpoint

- infrastructure/private-api.yaml
- infrastructure/public-api.yaml
Made the default status a HTTP 500 so that if the state unexpectedly fails (e.g. it does not exist), it won't just return a HTTP 200. 
The `StartSyncExecution` will return a `200 OK` response, even if execution fails, because the status code in the API response doesn't reflect function errors. 
- [OJ-2295](https://govukverify.atlassian.net/browse/OJ-2295)
[OJ-2295]: https://govukverify.atlassian.net/browse/OJ-2295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2295: Made default status HTTP 500 for state machines in VTL

- lambdas/credential-subject/src/credential-subject-builder.ts
- lambdas/credential-subject/src/credential-subject-handler.ts
- lambdas/credential-subject/src/user-info-event.ts
- lambdas/credential-subject/tests/credential-subject-builder.test.ts
- lambdas/credential-subject/tests/credential-subject-handler.test.ts
see https://govukverify.atlassian.net/browse/OJ-2436
This is the **first part** of introducing, birthdate into nino check VC
Next would be to incorporate birthday into the VC
According to https://govukverify.atlassian.net/wiki/spaces/Architecture/pages/3819930131/NINO+record+check+Technical+specification
This was used intially  https://github.com/govuk-one-login/architecture/blob/main/rfc/0024-identity-vc-for-checks.md#example-16---valid-national-insurance-number
- [OJ-2436](https://govukverify.atlassian.net/browse/OJ-2436)
[OJ-2436]: https://govukverify.atlassian.net/browse/OJ-2436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2436: include birthdate cred subject

- integration-tests/tests/aws/nino_issue_credential/nino_issue_credential.test.ts
- integration-tests/tests/mocked/nino-issue-credential/MockConfigFile.json
- integration-tests/tests/mocked/nino-issue-credential/nino-issue-credential-happy.test.ts
- step-functions/nino_issue_credential.asl.json
PART 2 see PART 1: https://github.com/govuk-one-login/ipv-cri-check-hmrc-api/pull/168
Update VC structure to include birthDate
VC structure to now contain birthDate according to https://govukverify.atlassian.net/wiki/spaces/Architecture/pages/3819930131/NINO+record+check+Technical+specification#Successful-NINO-check
Original implementation referenced VC structure to now contain birthDate according to https://govukverify.atlassian.net/wiki/spaces/Architecture/pages/3819930131/NINO+record+check+Technical+specification#Successful-NINO-check
- [OJ-2436](https://govukverify.atlassian.net/browse/OJ-2436)
[OJ-2436]: https://govukverify.atlassian.net/browse/OJ-2436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2436: Reflecting inclusion of birthday in integration-tests

- .secrets.baseline
- integration-tests/tests/mocked/nino-issue-credential/MockConfigFile.json
- integration-tests/tests/mocked/nino-issue-credential/makefile
- integration-tests/tests/mocked/nino-issue-credential/nino-issue-credential-unhappy.test.ts
Follow up to https://github.com/govuk-one-login/ipv-cri-check-hmrc-api/pull/176
- Added more test coverage for instance, when bearer token is invalid
- Added test for when there is a Ci in the generated VC
the issue/credential endpoint needs to return the Content-Type as application/jwt however its coming back as application/json . Issue is VTL related.
To stop return Content-Type as application/jwt 
- [OJ-2444](https://govukverify.atlassian.net/browse/OJ-2444)
[OJ-2444]: https://govukverify.atlassian.net/browse/OJ-2444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2444: Add mock test when bearer token is invalid

- .github/workflows/post-merge-deploy-to-build.yml
- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/run-aws-tests.yml
- .github/workflows/run-mocked-tests.yml
- .github/workflows/run-unit-tests.yml
- .gitignore
- .pre-commit-config.yaml
- infrastructure/template.yaml
added cloudwatch alarms for express step functions
re-ordering functions into an ordered consecutive block
updated actions versions to remove deprecation warnings
To enable alerting of function and api gateway errors
- [IPS-617](https://govukverify.atlassian.net/browse/IPS-617)
- [IPS-497](https://govukverify.atlassian.net/browse/IPS-497)
- 
[IPS-617]: https://govukverify.atlassian.net/browse/IPS-617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-497]: https://govukverify.atlassian.net/browse/IPS-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-617 cloudwatch alarms for express step functions

- infrastructure/private-api.yaml
Updated the private-api.yml file to include the 403 response for /authorization endpoint 
Updated the private-api.yml file to include the 403 response for /authorization endpoint 
To run unit tests in the check-hmrc-front repo  
- [OJ-2347](https://govukverify.atlassian.net/browse/OJ-2347)
[OJ-2347]: https://govukverify.atlassian.net/browse/OJ-2347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2347: Create 403 on Auth Endpoint

- integration-tests/tests/mocked/nino-check/MockConfigFile.json
- integration-tests/tests/mocked/nino-check/makefile
- integration-tests/tests/mocked/nino-check/nino-check-happy.test.ts
- integration-tests/tests/mocked/nino-check/nino-check-unhappy.test.ts
- step-functions/nino_check.asl.json
The nino-check state machine was not generating an auth code on the 2nd attempt which was causing a 3rd retry. The change made here makes it so that that if the user is on their last attempt, the auth code generation flow is triggered.
Unit tests have been fixed to work with the refactoring. 
Added new unit test to test the new flow. 
- [OJ-2445](https://govukverify.atlassian.net/browse/OJ-2445)
[OJ-2445]: https://govukverify.atlassian.net/browse/OJ-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2445: Fix State Machine not generating auth code on 2nd check attempt

- infrastructure/template.yaml
The `template.yaml` has been updated to include metrics. 
Metrics collected are:
- Metrics on successful NINO checks
- Metrics on retry sent
- Metrics on failed HMRC authentication
- Metrics on generic HMRC API errors
- Metrics on Matching Lambda exceptions
- Metrics on deceased users
- Metrics on attempts exceeded
- Metrics on invalid sessions
- Metrics on when a CI is raised
- Metrics on when a VC is issued
- [OJ-2450](https://govukverify.atlassian.net/browse/OJ-2450)
[OJ-2450]: https://govukverify.atlassian.net/browse/OJ-2450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2450: Added metrics

- infrastructure/template.yaml
Added namespace as the CRI identifier so that all the metrics for check-hmrc are grouped together. 
This does not include dimensions in the metric due to the following bug: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-logs/issues/108
- [OJ-2450](https://govukverify.atlassian.net/browse/OJ-2450)
[OJ-2450]: https://govukverify.atlassian.net/browse/OJ-2450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2450: Update Metrics namespace

- integration-tests/tests/mocked/check-session/MockConfigFile.json
- integration-tests/tests/mocked/check-session/check-session.test.ts
- integration-tests/tests/mocked/nino-issue-credential/MockConfigFile.json
- integration-tests/tests/mocked/nino-issue-credential/nino-issue-credential-happy.test.ts
- step-functions/check_session.asl.json
- step-functions/nino_issue_credential.asl.json
Make the Persistent Session Id optional
**Check Session was:**
**Now:**
Core integration broke in staging due to the assumption that it was always present in the JAR request
- [OJ-2479](https://govukverify.atlassian.net/browse/OJ-2479)
[OJ-2479]: https://govukverify.atlassian.net/browse/OJ-2479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2479: make persistent id optional

- .pre-commit-config.yaml
- infrastructure/template.yaml
Added state machine cloudwatch monitoring and alerting
Excluded cloudformation template from prettier updates
To enable state machine monitoring and alerting and to prevent prettier from formatting the cloud formation template
- [IPS-635](https://govukverify.atlassian.net/browse/IPS-635)
- [IPS-617](https://govukverify.atlassian.net/browse/IPS-617)
- 
[IPS-635]: https://govukverify.atlassian.net/browse/IPS-635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-617]: https://govukverify.atlassian.net/browse/IPS-617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-635 state machine alarms

- infrastructure/template.yaml
- Implement Subscription filter for CSLS logging
- Add CSLSEGRESS ARNs for all the environments
- Add subscription filters for the lambda functions and state machines.
- Add subscription filters to inject logs into splunk
- [IPS-676](https://govukverify.atlassian.net/browse/IPS-676)
[IPS-676]: https://govukverify.atlassian.net/browse/IPS-676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-676: Implement subscription filter for CSLS logging

- infrastructure/template.yaml
The condition for subscription filter has been widen to exclude localdev
i.e. `IsNotDevLikeEnvironment` which covers localdev and dev
Don't need them while deploying stacks for localdev
Subscription filters added for higher environment
local dev was broken
- [IPS-676](https://govukverify.atlassian.net/browse/IPS-676)
- [OJ-2489](https://govukverify.atlassian.net/browse/OJ-2489)
[IPS-676]: https://govukverify.atlassian.net/browse/IPS-676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-2489]: https://govukverify.atlassian.net/browse/OJ-2489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2489: Need to exclude for localdev

- infrastructure/template.yaml
- integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts
- integration-tests/tests/mocked/nino-check/MockConfigFile.json
- lambdas/otg-api/jest.config.ts
- lambdas/otg-api/package.json
- lambdas/otg-api/src/otg-api-handler.ts
- lambdas/otg-api/tests/otg-api-handler.test.ts
- lambdas/otg-api/tsconfig.json
- package-lock.json
- step-functions/nino_check.asl.json
* Created a Lambda that can call the OTG API and check expiry
* Created unit tests for the new Lambda
* Updated the state machine to use the OTG Lambda in place of the Get Secret Value
* Updated "Fetch SSM Parameters" state to fetch OTG URL based on the `clientId`
* Added CSLS SubscriptionFilter for OTG Lambda
* Added Error Metric Filter for OTG Lambda
* Added CloudWatch Alarm for OTG Lambda
- [OJ-2490](https://govukverify.atlassian.net/browse/OJ-2490)
[OJ-2490]: https://govukverify.atlassian.net/browse/OJ-2490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2490: Use the OTG API

- .github/workflows/deploy-branch.yml
changed environment value from `dev` to `localdev`
To run integration tests using the private API endpoints
- [OJ-2484](https://govukverify.atlassian.net/browse/OJ-2484)
[OJ-2484]: https://govukverify.atlassian.net/browse/OJ-2484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: changed env to local dev

- infrastructure/private-api.yaml
The /abandon endpoint expects the content-type header to be set as `application/json`. This change has been added to the OpenAPI spec to reflect this.
> Reflect content-type in /abandon OpenAPI 

- infrastructure/template.yaml
- integration-tests/step-functions/aws/nino_issue_credential/nino_issue_credential.test.ts
- integration-tests/step-functions/mocked/nino-issue-credential/MockConfigFile.json
- lambdas/ci-mapping/src/ci-mapping-event-validator.ts
- lambdas/ci-mapping/src/ci-mapping-handler.ts
- lambdas/ci-mapping/src/utils/ci-mapping-util.ts
- lambdas/ci-mapping/tests/ci-mapping-event-validator.test.ts
- lambdas/ci-mapping/tests/ci-mapping-handler.test.ts
- lambdas/ci-mapping/tests/utils/ci-mapping-utils.test.ts
- step-functions/audit_event.asl.json
- step-functions/nino_issue_credential.asl.json
see: https://govukverify.atlassian.net/browse/OJ-2458
This include the reasons behind related to CIs in audit events
Audit to include CI reason and IPV_CHECK_HMRC_CRI_VC_ISSUED event updated to include CI reasons
So that counter-fraud teams can use this as part of their investigation
- [OJ-2458](https://govukverify.atlassian.net/browse/OJ-2458)
[OJ-2458]: https://govukverify.atlassian.net/browse/OJ-2458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2458 vc issued audit event

- integration-tests/step-functions/aws/nino_issue_credential/nino_issue_credential.test.ts
- step-functions/nino_issue_credential.asl.json
The issue credential state machine now checks if `evidence_requested` is present in the session table. If it is, CIs are added to the VC. If the field is not present then no CI will be added to the VC.
Screenshot of the updated area:
- [OJ-2453](https://govukverify.atlassian.net/browse/OJ-2453)
[OJ-2453]: https://govukverify.atlassian.net/browse/OJ-2453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2453: Check for `evidence_requested` before adding CI into VC

- infrastructure/template.yaml
Enable Audit EventBus up to staging
Enabling up to staging, would allow testing integration with TxMA Team. Once this is done the condition can be removed entirely. i.e. The EventBusState would be set to ENABLED by default, then enabled by default in all environments
- [OJ-2420](https://govukverify.atlassian.net/browse/OJ-2420)
[OJ-2420]: https://govukverify.atlassian.net/browse/OJ-2420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2420: Enable Audit EventBus up to staging environment only

- infrastructure/private-api.yaml
This PR adjust VTL of /Check endpoint, to pull in
other header values like
i.e. txma-audit-encoded, X-Forwarded-For etc
We need to be able to optionally pull in `txma-audit-encoded`
> OJ-2501: Adjust /Check endpoint to deal with headers

- infrastructure/template.yaml
Remove EventBusState
The eventbus Rules are all Disabled using !Ref EventBusState
Directly state the `State` to ENABLED should work
- [OJ-2420](https://govukverify.atlassian.net/browse/OJ-2420)
[OJ-2420]: https://govukverify.atlassian.net/browse/OJ-2420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2420: Remove EventBusState Entirely

- infrastructure/template.yaml
- integration-tests/package.json
- integration-tests/resources/event-bridge-helper.ts
- integration-tests/resources/queue-helper.ts
- integration-tests/resources/util.ts
- integration-tests/step-functions/aws/abandon/abandon.test.ts
- integration-tests/step-functions/aws/nino-check/nino-check-happy.test.ts
- integration-tests/step-functions/aws/nino_issue_credential/nino_issue_credential.test.ts
- package-lock.json
To test AWS Step Function putevents integration, the eventbridge and the event rules, this PR create test queues and adds them as target to the existing rules and the eventbus. The messages returned shows that the integration works, also the data items sent can be inspected in the test to ensure the look as expected.
Currently no test exists to ensure that the putevent integration in the step function works
as per of reviewing https://govukverify.atlassian.net/browse/OJ-2421 this PR address that the first part.
Since https://govukverify.atlassian.net/wiki/spaces/OJ/pages/3947331850/Pre-merge+testing+of+TXMA+messages the implementation involved eventbrigde and rules which isn't covered in the write up above.
Using the same idea of the write-up test queues are used to test the putevent …
> OJ-2421: pre-merge testing TxMa

- infrastructure/template.yaml
- step-functions/audit_event.asl.json
A meaningful monitoring and alarms for the EventBridge rules
Added FailedInvocation Alarm for Audit Event Eventbridge Rules in Nino CRI, Eventbridge rules have many alarms but this seems like a good place to start. This PR doesn't consider what happens to messages when things fails. 
NB: The way events are made available to the TxMA queue has been refactored in this PR. This now uses a new Event bridge rule `TxMaAuditEventRule` , which needs a FailedInvocation Alarm also included in this PR
See: https://gds.slack.com/archives/C06TX3H2XPS/p1715241837577809
- [OJ-2556](https://govukverify.atlassian.net/browse/OJ-2556)
[OJ-2556]: https://govukverify.atlassian.net/browse/OJ-2556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2556: Added Alarm for FailedInvocation Metric to EventBridge Rules (PART 1)

- infrastructure/template.yaml
A meaningful monitoring and alarms for the EventBridge Bus
This is the second PR for PutEvent to the EventBus
Added PutEvents Failed Alarm for Audit Event Eventbridge Bus in Nino CRI, Eventbridge Bus has other alarms but this seems like a good place to start. This PR doesn't consider what happens to messages when things fails. 
See: https://gds.slack.com/archives/C06TX3H2XPS/p1715241837577809
- [OJ-2556](https://govukverify.atlassian.net/browse/OJ-2556)
[OJ-2556]: https://govukverify.atlassian.net/browse/OJ-2556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2556: Eventbus Alarms

- infrastructure/template.yaml
Added Missing AlarmName for CheckHmrcEvent Bus Alarm.
Where its clear what happened it is Included in the alarm of the name
All alarm name end with `-alarm`
Names follow this pattern
`{CRI-NAME}-{ENVIRONMENT}-{COMPONENT-NAME}-{ERROR-TYPE}-alarm`
> OJ-2556: Make alarm name even more consistent

- integration-tests/step-functions/aws/abandon/abandon.test.ts
- integration-tests/step-functions/aws/nino-check/nino-check-happy.test.ts
- integration-tests/step-functions/mocked/abandon/MockConfigFile.json
- integration-tests/step-functions/mocked/abandon/abandon.test.ts
- integration-tests/step-functions/mocked/check-session/check-session.test.ts
- integration-tests/step-functions/mocked/nino-check/MockConfigFile.json
- integration-tests/step-functions/mocked/nino-check/nino-check-happy.test.ts
- step-functions/abandon.asl.json
- step-functions/audit_event.asl.json
- step-functions/check_session.asl.json
- step-functions/nino_check.asl.json
Check input for the txma header if present get the header value if not set an empty string {}. To use, the header can be published as part of the event that need it.
To allow the inclusion of device information in audit events
- [OJ-2501](https://govukverify.atlassian.net/browse/OJ-2501)
[OJ-2501]: https://govukverify.atlassian.net/browse/OJ-2501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2501: Add txma audit header to check_session

- infrastructure/template.yaml
- lambdas/pii-redact/jest.config.ts
- lambdas/pii-redact/package.json
- lambdas/pii-redact/src/pii-redact-handler.ts
- lambdas/pii-redact/src/pii-redactor.ts
- lambdas/pii-redact/tests/pii-redact-handler.test.ts
- lambdas/pii-redact/tests/redact-pii.test.ts
- lambdas/pii-redact/tsconfig.json
- package-lock.json
- package.json
The way we censor PII. 
* New log groups for PII redacted logs for Splunk
* Subscription Filter to a new Lambda that handles the censoring
The way the logic here works is:
1. Created new log groups that contain PII redacted logs
2. Updated the CSLS subscriptions to use those new log groups so Splunk gets redacted logs
3. Created a PII redact lambda 
4. Set a subscription filter to the original log groups that calls the lambda. 
The lambda created receives the logs, masks the PII and forwards the logs to the PII redacted variant. 
We need structured JSON in Splunk which the old way didn't do properly. 
- [OJ-2319](https://govukverify.atlassian.net/browse/OJ-2319)
[OJ-2319]: https://govukverify.atlassian.net/browse/OJ-2319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> OJ-2319: Created new log groups for PII and PII Redact Lambda

- lambdas/pii-redact/src/pii-redactor.ts
This PR uses a generic regex to censor IP addresses. This was added because the current way of censoring IP addresses in blocks we know of isn't going to capture areas we did not identify. 
OK-2319
> OJ-2319: Added generic IP Address redaction

- infrastructure/template.yaml
Increase log group's RetentionInDays to 30. Currently any log retention that is set under 30 days will be set to 30 by a Lambda attached to the LZA Lambda run - [INCIDEN-627](https://govukverify.atlassian.net/browse/INCIDEN-627?focusedCommentId=125675)
What changed
RetentionInDays: changed RetentionInDays: 30
Check ticket https://govukverify.atlassian.net/jira/software/c/projects/PSREC/boards/555?selectedIssue=PSREC-243 and associated epic https://govukverify.atlassian.net/browse/PSREC-314
Why did it change
LZA lambda unpicks log retentions lower than 30 days.
Issue tracking
[INCIDEN-627](https://govukverify.atlassian.net/browse/INCIDEN-627?focusedCommentId=125675)
Environment variables or secrets
[ ] No environment variables or secrets were added or changed
[ ] Documented in the …
> removed conditional and modified RetentionInDays values to 30

- .github/workflows/check-pr.yml
- .github/workflows/run-evn-abn-tests.yml
- .github/workflows/run-evn-nino-tests.yml
- .github/workflows/run-sfn-aws-tests.yml
- integration-tests/eventbridge/abandon/abandon-publish.test.ts
- integration-tests/eventbridge/nino-check/nino-check-publish.test.ts
- integration-tests/eventbridge/nino_issue_credential/nino-issue-credential-publish.test.ts
- integration-tests/resources/queue-helper.ts
- integration-tests/resources/util.ts
The event bridge tests that were run pre-merge were intermittently failing. 
They had the following issues:
* Not cleaning up after themselves properly
* Taking too long (e.g. some cases they took 10-15 minutes each)
* Interfering with each other
The clean up code in itself wasn't wrong however the way the awaits, retries and promises were done, caused the scripts to be long running and timeout before they could properly clean up. 
This PR fixes the clean up issues after each test and lowers the time the tests wait and re-try on failure. Refactored the `@AfterEach` blocks to run in sequence and not parallel. 
The GHAs are now also running in sequence instead of parallel to avoid any conflicts between them. This is because if we ran an APIGW test, that test would be publishing audit events …
> BAU: Fix intermittent failures with event bridge tests

- infrastructure/private-api.yaml
VTL for /check to not try to exclude the "session-id" header
The parsing logic was causing invalid JSON to be produces so to avoid adding extra complexity to the VTL, I have removed that logic. The reason it was added was because we provide a "sessionId" already so now we will also get a "session-id" which does not cause any functional issues. 
- [OJ-2629](https://govukverify.atlassian.net/browse/OJ-2629)
[OJ-2629]: https://govukverify.atlassian.net/browse/OJ-2629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2629: Remove session-id exclusion in VTL

- infrastructure/private-api.yaml
- infrastructure/public-api.yaml
- integration-tests/api-gateway/check/check-happy.test.ts
Added `$util.escapeJavaScript` to all the bits that in OpenAPI spec that come from user input.
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html
- [OJ-2610](https://govukverify.atlassian.net/browse/OJ-2610)
[OJ-2610]: https://govukverify.atlassian.net/browse/OJ-2610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2610: Escape JavaScript in VTL

- deploy.sh
- infrastructure/template.yaml
- Added `DeadLetterConfig` for `TxMaAuditEventRule`
- Set `CommonInfrastructureStackName` as a parameter so we can easily point to custom stacks
So that messages that fail to reach the Audit event queue reach the audit event dead letter queue
- [OJ-2618](https://govukverify.atlassian.net/browse/OJ-2618)
[OJ-2618]: https://govukverify.atlassian.net/browse/OJ-2618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2618: Audit event rule DLQ

- infrastructure/template.yaml
Adds `POWERTOOLS_SERVICE_NAME` to be used by @aws-lambda-powertools/logger as [service](https://docs.powertools.aws.dev/lambda/typescript/latest/core/logger/#utility-settings)
So that the service name is logged instead of `service_undefined`
**Before** 
**After**
> BAU: Fix service_undefined in logger

- infrastructure/template.yaml
- lambdas/matching/src/matching-handler.ts
- lambdas/matching/src/metric-types.ts
- lambdas/matching/tests/matching-handler.test.ts
Added custom metrics and info log for response latency in the matching lambda.
This allows us to separate the response times of third parties (or stubs) from the overall response times. 
DT board to follow once the metric has been merged.
- [OJ-2632](https://govukverify.atlassian.net/browse/OJ-2632)
[OJ-2632]: https://govukverify.atlassian.net/browse/OJ-2632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2632: Adds custom metrics for response latency

- .secrets.baseline
- infrastructure/template.yaml
- integration-tests/step-functions/aws/nino_issue_credential/nino_issue_credential.test.ts
- lambdas/jwt-signer/src/jwt-signer-handler.ts
- lambdas/jwt-signer/src/signer-payload.ts
- lambdas/jwt-signer/tests/jwt-signer-handler.test.ts
- lambdas/jwt-signer/tests/test-data.ts
Added the Hashed kid in the JWT header
Due to the [RFC 71](https://github.com/govuk-one-login/architecture/blob/c3e867fbd746237ec8715760e3995782e319231f/rfc/0071-opque-kid-claims.md#kms-key-aliases:~:text=When%20producing%20a%20hash%2C%20we%20need%20to%20ensure%20we%20are%20using%20the%20underlying%20KMS%20Key%20ID%20and%20not%20the%20alias) points out that this should not be a hash of the KMS Key ID
- [OJ-2721](https://govukverify.atlassian.net/browse/OJ-2721)
[OJ-2721]: https://govukverify.atlassian.net/browse/OJ-2721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ 2721 kid

- infrastructure/template.yaml
- integration-tests/step-functions/mocked/check-session/check-session.test.ts
- integration-tests/step-functions/mocked/nino-check/MockConfigFile.json
- step-functions/check_session.asl.json
- step-functions/nino_check.asl.json
Added a TTL to the `user-attempts` and `nino-users` table. The TTL set is 2 hours.
This was added because once sessions had expired, we did not remove the data from the database. This meant our DB will retain the records and continue to grow, taking up resources. The information stored in those tables are only required when the user is performing a NINO check, once they get a VC, the information is no longer needed. 
**Screenshot**
- [OJ-2773](https://govukverify.atlassian.net/browse/OJ-2773)
[OJ-2773]: https://govukverify.atlassian.net/browse/OJ-2773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2773: Add TTL to `user-attempts` and `nino-users` table

- integration-tests/step-functions/aws/nino_issue_credential/nino_issue_credential.test.ts
- lambdas/ci-mapping/src/ci-mapping-event-validator.ts
- lambdas/ci-mapping/src/ci-mapping-handler.ts
- lambdas/ci-mapping/tests/ci-mapping-handler.test.ts
Ignore case when searching for CI mappings
To make the system more resilient - we have conflicting information about the cases and this was the safest way to ensure success in prod
Mappings stay as is
Error string case doesn't match mapping
Correct CI is still generated
Step function still passes
- [OJ-2788](https://govukverify.atlassian.net/browse/OJ-2788)
[OJ-2788]: https://govukverify.atlassian.net/browse/OJ-2788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2788: Ignore case when searching for CI mappings

- infrastructure/template.yaml
The InvokeLambda role was not being used so this has been removed
> BAU: Removed unused IAM role

- infrastructure/template.yaml
- Existing lambda alarms were removed
- Added the `CheckHmrcLambdaErrors` alarm to capture all lambda errors (and follow the same standard as Address and KBV)
- Added the `CheckHmrcLambdaThrottle` alarm to capture all lambda throttle
- Updated the state machine alarms to use `core-infrastructure-AlarmTopic` and `platform-alarm-critical-alert-topic` to increase the level to critical and link it to PagerDuty
- Removed incorrect metric filters
The lambda alarms in NINo were using metrics with `FilterPattern` that are related to step functions rather than the lambdas making them impossible to hit and test. So the alarm were updated to follow the same standard as in Address and KBV. Also the existing state machine alarms are elevated to critical and linked to the PagerDuty. 
- …
> OJ-2793: Removed the lamda alarms and metric fileters. Added general lambda alarm and updated the state machine alarms to be critical

- README.md
- infrastructure/private-api.yaml
- infrastructure/public-api.yaml
- infrastructure/template.yaml
Lambda and step function canary deployment configured
- Set deployment preference for lambda and step function, by default set to AllAtOnce
- Enabled versioning for lambda using autopublishalias live in globals
- Enabled versioning for step functions using autopublishalias live in individual step function
- Added code deploy role for lambda canary deployment
- Created alarms Execution failed alarm and lambda error alarms
- For state machines, I associated both the step function and relevant lambda alarms in the state machine configuration
- For one lambda that is not called using a step function PII Redact, I set the configuration in that lambda
- from api gateway and eventbus, pointed the state machine to the live version e.g. "stateMachineArn": "${XXXXXStateMachine.Arn}:live" to make …
> Ips 1101 step function and lambda canaries

- lambdas/matching/src/matching-handler.ts
- lambdas/matching/tests/matching-handler.test.ts
The matching-handler will return the body as text instead of JSON if the content-type is application/json but the body is not valid JSON.
HMRC send plain text for HTTP 422 and they also set the responses `Content-Type` as `application/json` so when our code sees this, we try to parse the response body as JSON. As the body isn't valid JSON our code throws an exception. To fix this, we instead read the body as text when the body is not valid JSON.
- [OJ-2806](https://govukverify.atlassian.net/browse/OJ-2806)
[OJ-2806]: https://govukverify.atlassian.net/browse/OJ-2806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2806: return text body instead when content-type is application/json and body is invalid json

- lambdas/matching/src/matching-handler.ts
- lambdas/matching/tests/matching-handler.test.ts
In TypeScript we cannot fall-back to text after trying to read the body as JSON. To mitigate this, we parse the body as text first and then try to parse as JSON.
- [OJ-2806](https://govukverify.atlassian.net/browse/OJ-2806)
[OJ-2806]: https://govukverify.atlassian.net/browse/OJ-2806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2806: use text body and then try-parse to json

- infrastructure/template.yaml
Alarms enabled action set to true.
These are canary alarms. Originally set to false because if they were set to true when deploying they would trigger and send notifications to slack. Part of canary work [here](https://github.com/govuk-one-login/ipv-cri-check-hmrc-api/pull/412)
- [IPS-1101](https://govukverify.atlassian.net/browse/IPS-1101)
[IPS-1101]: https://govukverify.atlassian.net/browse/IPS-1101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1101 enabling canary alarms

- infrastructure/template.yaml
Added a generic alarm `CheckHmrcLambdaConcurrency80Alarm` which fires when over 80% of concurrent executions is used. In this PR, there is 1 alarm to cover them all to follow the current alarm pattern we have defined.
**Screenshot**
- [OJ-2779](https://govukverify.atlassian.net/browse/OJ-2779)
[OJ-2779]: https://govukverify.atlassian.net/browse/OJ-2779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2779: Create alarm for when 80% of concurrent Lambda executions is used

- infrastructure/samconfig.toml
- lambdas/matching/src/match-event.ts
- lambdas/matching/src/matching-handler.ts
- lambdas/matching/src/name-part.ts
- lambdas/matching/tests/matching-handler.test.ts
- step-functions/nino_check.asl.json
1. The `NinoCheckStateMachine` now provides the entire Name structure to the `MatchingHandler` Lambda instead of trying to parse the `GivenName` and `FamilyName`
2. The `MatchingHandler` concatenates all the `FamilyName`s and converts it into a single space-delimited string. Secondaly, the `MatchingHandler` will choose the first `GivenName`
This change was implemented because users can have multiple surnames so we send them all to HMRC. 
Example:
GivenName: John
FamilyName: [Bob, Alice, Eve]
The request sent to HMRC will be:
firstName: John
lastName: Bob Alice Eve
Secondly, we choose the first GivenName from the array to mitigate any risks of the RP providing us with data in an order we do not expect. 
- [OJ-2822](https://govukverify.atlassian.net/browse/OJ-2822)
[OJ-2822]: …
> OJ-2822: Concat FamilyName's before sending request to HMRC

- integration-tests/step-functions/mocked/nino-issue-credential/MockConfigFile.json
- integration-tests/step-functions/mocked/nino-issue-credential/nino-issue-credential-unhappy.test.ts
- step-functions/nino_issue_credential.asl.json
NinoIssueCredential state machine, the state "Query Session Item" now uses a DynamoDB query instead of a Scan
When using a Scan we sometimes get a `LastEvaluatedKey` in the task response. This means that the Scan operation has not completed. We do not continue the Scan so the state machine falls over as it cannot find the session associated with a given `accessToken`. The fix implemented here is:
1. Query the the `sessionId` from the `accessToken` using the `"access-token-index` index.
2. Query the session record from the resolved `sessionId` from the 1st DynamoDB query
This fix is what is done in cri-lib and also by Lime Team in their state machines.
Note: We understand the issues of using the GSI however this fix is to reduce the error rate. GSI is being investigated by the programme. …
> OJ-2552: Use Query instead of Scan for "Query Session Item" in NinoIssueCredentialStateMachine

- infrastructure/template.yaml
- lambdas/sleep-function/jest.config.ts
- lambdas/sleep-function/package.json
- lambdas/sleep-function/src/sleep-function.ts
- lambdas/sleep-function/tests/sleep-function.test.ts
- lambdas/sleep-function/tsconfig.json
- package-lock.json
- step-functions/delete-person-identity-records.asl.json
- step-functions/delete-records.asl.json
Create a new state machine to delete all records in the person identity table
We have a load of records that do not have valid TTLs. TTLs have been added to the table however the old records were not cleaned up. This PR deletes those records as Check HMRC is not live in production so we can benefit from just deleting all the records.
**Screenshot**
**Before**
**After**
- [OJ-2798](https://govukverify.atlassian.net/browse/OJ-2798)
[OJ-2798]: https://govukverify.atlassian.net/browse/OJ-2798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2798: Delete records with no TTL

- infrastructure/template.yaml
- step-functions/delete-attempts-records.asl.json
The test data being used did not accurately reflect what was in the higher accounts. When doing a DynamoDB delete, we do not have to worry about using a LastEvalutedBy 
- [OJ-2798](https://govukverify.atlassian.net/browse/OJ-2798)
[OJ-2798]: https://govukverify.atlassian.net/browse/OJ-2798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2798: Fix delete state machine

- infrastructure/template.yaml
- lambdas/pii-redact/src/pii-redact-handler.ts
- lambdas/pii-redact/tests/pii-redact-handler.test.ts
- package-lock.json
- package.json
When we create a log stream, if it already exists, the CloudWatch API will return a HTTP 400. While, for our Lambda this is OK as we ignore the error, the side effect is that Dynatrace alerts that there are errors which means our dashboard will always be red.
To solve this, we create a new DynamoDB table that keeps track of all the log streams that we create (with a TTL of 2 hours). We use this table in our Lambda to check if we should create a new log stream not.
We do not use the DescribeLogStream API because that has a limit of 5 executions per second which does not fit our requirements.
- [OJ-2897](https://govukverify.atlassian.net/browse/OJ-2897)
[OJ-2897]: https://govukverify.atlassian.net/browse/OJ-2897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …
> OJ-2897: Track LogStream creations in DynamoDB and only create if not previously created

- infrastructure/template.yaml
Linear10PercentEvery1Minute allowed value added for canary deployment
Value required for lambda canary deployment in lower envs
Dev and build will use Linear10PercentEvery1Minute therefore this is required value
> Linear10PercentEvery1Minute allowed value added

- infrastructure/template.yaml
Refactored StateMachine alarms to treatMissingData as notBreaching.
Refactored StateMachine alarms to make the alarm match the description.
The alarms are transition to OK every morning due to MissingData being treated as missing. These alarms all trigger slack messages causing the channel to get spammed. 
Also, previously the alarms did not match the description, rather than 4 failures within an hour, it was atleast 1 failure in 4 different 5 minute periods within an hour. This would mean if for example, if 100 executions failed but only within a 5 minute period it would not trigger the alarm. 
https://github.com/govuk-one-login/ipv-cri-otg-hmrc/pull/167
Note: See alarm threshold is `ExecutionsFailed > 0 for 4 datapoints within 1 hour`, to match the description (`... failed 4 or more …
> BAU: Minor refactor to state machine alarms

- lambdas/pii-redact/src/pii-redactor.ts
- lambdas/pii-redact/src/regex/contra-indicator.ts
- lambdas/pii-redact/tests/redact-pii.test.ts
Added contra-indicator.ts to redaction Lambda
We should not be logging CIs and their reasons to Splunk.
- [OJ-2932](https://govukverify.atlassian.net/browse/OJ-2932)
[OJ-2932]: https://govukverify.atlassian.net/browse/OJ-2932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2932: Redact CI and reasons from logs

- infrastructure/private-api.yaml
- integration-tests/api-gateway/check/check-happy.test.ts
- integration-tests/api-gateway/e2e/e2e-happy-path.test.ts
- integration-tests/api-gateway/e2e/e2e-retry-path.test.ts
- integration-tests/eventbridge/nino-check/nino-check-publish.test.ts
- integration-tests/step-functions/aws/nino-check/nino-check-happy.test.ts
- integration-tests/step-functions/aws/nino-check/nino-check-unhappy.test.ts
- integration-tests/step-functions/mocked/nino-check/nino-check-happy.test.ts
- integration-tests/step-functions/mocked/nino-check/nino-check-unhappy.test.ts
- step-functions/nino_check.asl.json
To be merged after successful deployment of: https://github.com/govuk-one-login/ipv-cri-check-hmrc-front/pull/315
Updated retry logic to return a http 200 and body containing `requestRetry: true`
The previous http 422 was causing our dashboards to go red since it was considered a 4xx error. 
- [OJ-2921](https://govukverify.atlassian.net/browse/OJ-2921)
[OJ-2921]: https://govukverify.atlassian.net/browse/OJ-2921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: http 200 for retry and return requestRetry to signify if the FE should retry

- infrastructure/private-api.yaml
Removed the 422 status from the private-api.yaml as this is no longer returned by the API
- [OJ-2921](https://govukverify.atlassian.net/browse/OJ-2921)
[OJ-2921]: https://govukverify.atlassian.net/browse/OJ-2921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: remove 422 response from openapi spec

- infrastructure/template.yaml
Allowed values for lambda deployment preference removed to allow any values.
This change was required to allow any values to be passed in the pipeline parameter. I was going to add the allowed value of LambdaCanary50Percent5Minutes as that is what is set in the pipeline but we may want to make changes in the future so this will remove the need to update this template again when pipeline parameter changes.
This will be in line with address and kbv as they dont specify allowed values.
- [IPS-1289](https://govukverify.atlassian.net/browse/IPS-1289)
[IPS-1289]: https://govukverify.atlassian.net/browse/IPS-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1289 allowed values for lambda deployment preference removed

- infrastructure/template.yaml
Implementation for 50Percent 5Minute canary traffic shifting for non prod envs.
State machine conditional added that sets deployment to 50Percent 5Minutes for non prod env. 
Interval: !If [IsProdEnvironment, 15, 5]
Percentage: !If [IsProdEnvironment, 10, 50]
This means if environment is not production, use 5 minute interval and 50 Percent, but if it is production, then use the agreed strategy 10Percent 15 minutes.
The non prod strategy is only enabled when the pipeline parameter is set to CANARY from ALLATONCE e.g. here for [build](https://github.com/govuk-one-login/identity-common-infra/blob/main/terraform/orange/hmrc-check/build/pipelines/main.tf#L25)
Setting 50 Percent 5 Minutes  state machine deployments means the pipeline can run faster and test changes in lower envs in a more even …
> Ips 1234 50 percent 5 minutes canary deployment

- infrastructure/template.yaml
PII redact alias permission added. 
This is to allow this function to be invoked using the alias. Alias is needed due to canary deployments and using versions. Alias is the live version of the lambda.
For backwards compatibility permission needs to be added first, and then the DestinationArn can be changed from !GetAtt PIIRedactFunction.Arn to !Ref PIIRedactFunction.Alias. Second [PR](https://github.com/govuk-one-login/ipv-cri-check-hmrc-api/pull/488) to follow. 
- [IPS-1120](https://govukverify.atlassian.net/browse/IPS-1120)
[IPS-1120]: https://govukverify.atlassian.net/browse/IPS-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1120 PII Redact alias permission added

- infrastructure/template.yaml
State machine canary 5xx error alarms added:
- AbandonStateMachineCanary5xxErrors
- NinoCheckStateMachineCanary5xxErrors
- NinoIssueCredentialStateMachineCanary5xxErrors
These alarms have been configured and added to their respective state machines.
5xx error alarms are useful in catching errors during canary deployments.
- [IPS-1120](https://govukverify.atlassian.net/browse/IPS-1120)
[IPS-1120]: https://govukverify.atlassian.net/browse/IPS-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1120 state machine 5xx canary alarms

- infrastructure/template.yaml
Memory set to 2GB for Lambdas
Performance improvements
- [OJ-2902](https://govukverify.atlassian.net/browse/OJ-2902)
[OJ-2902]: https://govukverify.atlassian.net/browse/OJ-2902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: set lambda memory to 2GB

- .github/workflows/scan-repo.yml
- coverage-run-id is passed into the SonarCloud action for none PRs so it does not run the Await coverage report step.
- Added workflow_dispatch to Scan repo action
Await coverage report was added to the sonarcloud github action which broke our Scan Repo action when running on a schedule. Passing in the workflow id to the action prevents this from happening.
- [OJ-3108](https://govukverify.atlassian.net/browse/OJ-3108)
[OJ-3108]: https://govukverify.atlassian.net/browse/OJ-3108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3108: Fix scan repo action for non PRs

- integration-tests/api-gateway/abandon/abandon-happy.test.ts
- integration-tests/api-gateway/abandon/abandon-unhappy.test.ts
- integration-tests/api-gateway/authorization/authorization-happy.test.ts
- integration-tests/api-gateway/authorization/authorization-unhappy.test.ts
- integration-tests/api-gateway/check/check-happy.test.ts
- integration-tests/api-gateway/check/check-unhappy.test.ts
- integration-tests/api-gateway/contract/utils/DatabasePopulator.ts
- integration-tests/api-gateway/contract/utils/PactJwtFormatter.ts
- integration-tests/api-gateway/e2e/e2e-happy-path.test.ts
- integration-tests/api-gateway/e2e/e2e-retry-path.test.ts
- integration-tests/api-gateway/jest.config.ts
- integration-tests/api-gateway/session/session-happy.test.ts
- integration-tests/api-gateway/session/session-unhappy.test.ts
- integration-tests/api-gateway/types.ts
- integration-tests/eventbridge/abandon/abandon-publish.test.ts
- integration-tests/eventbridge/jest.config.ts
- integration-tests/eventbridge/nino-check/nino-check-publish.test.ts
- integration-tests/eventbridge/nino_issue_credential/nino-issue-credential-publish.test.ts
- integration-tests/globalStackOutputSetup.ts
- integration-tests/step-functions/aws/abandon/abandon.test.ts
- integration-tests/step-functions/aws/check-session/check-session.test.ts
- integration-tests/step-functions/aws/jest.config.ts
- integration-tests/step-functions/aws/nino-check/nino-check-happy.test.ts
- integration-tests/step-functions/aws/nino-check/nino-check-unhappy.test.ts
- integration-tests/step-functions/aws/nino_issue_credential/nino_issue_credential.test.ts
Improve the individual time each integration test component was taken
Introduced a global api-test-context, which would get the stack information once, instead of in every test
Running test locally was a flakky adjusting the timeout locally often worked, these changes should result in a more consistent experience
- [OJ-3131](https://govukverify.atlassian.net/browse/OJ-3131)
[OJ-3131]: https://govukverify.atlassian.net/browse/OJ-3131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3131: improve individual integration test speed

- integration-tests/step-functions/aws/nino-check/nino-check-unhappy.test.ts
- lambdas/matching/src/matching-handler.ts
- lambdas/matching/tests/matching-handler.test.ts
- step-functions/nino_check.asl.json
* Added test for internal server error
* Updated `NinoCheckStateMachine` to check if the `code` value is present in the error handling block
* Updated the `MatchingFunction` to not return the API response body on 5xx errors. This is because their errors may contain PII and we cannot be sure that the error message will be consistent. 
The HMRC PDV matching API was down which caused an incident. While, functionally, this wasn't a problem for us, we didn't handle the exception properly in the step function. The same effect still occurred (i.e. step function execution failure) but this should ideally happen on our `Err: API Error.` fail state. 
Additionally, on any 5xx error, we return "Internal server error" as the parsed PDV matching response body. This is because we have seen PII being …
> OJ-3209: handle internal pdv errors better

- infrastructure/template.yaml
Add slack actions to lambda error alarm.
Improve visibility of lambda errors. 
- [OJ-3193](https://govukverify.atlassian.net/browse/OJ-3193)
[OJ-3193]: https://govukverify.atlassian.net/browse/OJ-3193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3193: Add slack actions to lambda error alarm

- infrastructure/template.yaml
Added APIGW 5XX alarm. 
This alarm has been copied from Address and KBV and kept the same for consistency. 
When we replace some state machines with lambdas, we will remove the current alarms in place. This ensure backend 5xx errors will still trigger an alarm.
- [OJ-3193](https://govukverify.atlassian.net/browse/OJ-3193)
[OJ-3193]: https://govukverify.atlassian.net/browse/OJ-3193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3193: Add APIGW 5xx alarm

- lambdas/pii-redact/src/pii-redact-handler.ts
- lambdas/pii-redact/tests/pii-redact-handler.test.ts
- lambdas/pii-redact/tests/utils.ts
Added exception handling to createLogStream() to resolve race condition where multiple simultaneous executions try to create the same log stream.
This morning (09/06/2025) we found that the CheckHmrcLambdaErrors alarm was being triggered repeatedly, causing Amazon Q to fill the #di-orange-critical-non-prod channel with errors. This has been traced to the PIIRedactFunction throwing the following error:
```json
{
"errorType": "ResourceAlreadyExistsException",
"errorMessage": "The specified log stream already exists",
"name": "ResourceAlreadyExistsException",
"$fault": "client",
"$metadata": {
"httpStatusCode": 400,
"requestId": "0f0efd2e-cf6c-4e77-b9ca-7029c12e2055",
"attempts": 1,
"totalRetryDelay": 0
},
"__type": "ResourceAlreadyExistsException",
"stack": [ …
```
> OJ-3220 - Handle ResourceAlreadyExistsException in PIIRedactFunction createLogStream()

- infrastructure/template.yaml
Add missing DeployAlarms conditions
Some alarms were being deployed when they shouldn't be and causing noise in alarms channels - eg preview stacks
Before 
After
> Add missing DeployAlarms conditions

- infrastructure/template.yaml
Update SupportManualURL to be a mapping
Because cloudformation params can't be easily updated. Note that this follows pattern from [mobile](https://github.com/govuk-one-login/mobile-id-check-async/blob/112899215e89db31f4d1412c4f04665a3a5133ca/backend-api/infra/monitoring/sqsAlarms.yaml#L10C35-L10C50)
Before
After
- [OJ-3214](https://govukverify.atlassian.net/browse/OJ-3214)
[OJ-3214]: https://govukverify.atlassian.net/browse/OJ-3214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3214: Update SupportManualURL to be a mapping

- infrastructure/template.yaml
Add failed to verify alarm
So that we are quickly alerted when there is an issue verifying the JWTs that core is sending check HMRC CRI. 
- [OJ-3083](https://govukverify.atlassian.net/browse/OJ-3083)
[OJ-3083]: https://govukverify.atlassian.net/browse/OJ-3083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3083: Add failed to verify alarm

- infrastructure/private-api.yaml
- infrastructure/public-api.yaml
To add canary deployment in common lambda functions, the api spec should point to the live alias of the common lambda function. 
Modified the api spec point to the live common lambda functions.
Changes for api spec point to live lambda functions. This changes made for the common lambda functions include 
Session function
Authorization function 
Access Token function.
To enable canaries for the common lambda function
- [IPS-1858](https://govukverify.atlassian.net/browse/IPS-1858)
[IPS-1858]: https://govukverify.atlassian.net/browse/IPS-1858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1858: Update api spec point to live alias of the lambda function

- infrastructure/template.yaml
Add condition to metric filer to only be on `PassStateExited`
VCIssuedMetric is reporting twice
- [OJ-3259](https://govukverify.atlassian.net/browse/OJ-3259)
[OJ-3259]: https://govukverify.atlassian.net/browse/OJ-3259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3259: Fix duplicated VCissuedMetric

- lambdas/common/src/util/metrics.ts
- lambdas/nino-check/src/handler.ts
Added [metrics decorator](https://docs.powertools.aws.dev/lambda/typescript/latest/core/metrics/#using-the-class-decorator) to NINo check handler
Metrics were not being consistently pushed to CloudWatch
- OJ-3197
> OJ-3197: Add metrics decorator to ensure metrics queue is flushed before Lambda spins down

- infrastructure/public-api.yaml
- infrastructure/template.yaml
- lambdas/common/src/types/access-token-index-session-item.ts
- lambdas/common/tests/config/function-config.test.ts
- lambdas/common/tests/mocks/mockData.ts
- lambdas/issue-credential/jest.config.ts
- lambdas/issue-credential/package.json
- lambdas/issue-credential/src/handler.ts
- lambdas/issue-credential/src/helpers/retrieve-nino-user.ts
- lambdas/issue-credential/src/helpers/retrieve-session-by-access-token.ts
- lambdas/issue-credential/tests/handler.test.ts
- lambdas/issue-credential/tests/helpers/retrieve-nino-user.test.ts
- lambdas/issue-credential/tests/helpers/retrieve-session-by-access-token.test.ts
- lambdas/issue-credential/tsconfig.json
- package-lock.json
- Added credential issuer function
- Is it within scope to be emitting metrics for this ticket? If so, which ones?
We are looking to move NINo check backend logic to Lambdas instead of step functions
- OJ-3227
- OJ-3190
> OJ-3227 - Implement initial issue-credential function

- integration-tests/package.json
- package-lock.json
Bump pact and wait-on, add form-data overrides
form-data vulnerability was fixed in axios 1.11.0 but pact and wait-on are still using old versions of axios.
Bumped to the latest version so that we're ready to upgrade when we can, added a forced override to use form-data 4.0.4 which is the patched version
https://github.com/axios/axios/pull/6970
- [OJ-3271](https://govukverify.atlassian.net/browse/OJ-3271)
[OJ-3271]: https://govukverify.atlassian.net/browse/OJ-3271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3271: Bump pact and wait-on, add form-data overrides

- infrastructure/template.yaml
- lambdas/issue-credential/src/handler.ts
- lambdas/issue-credential/tests/handler.test.ts
Removed dev Like condition
IssueCredential Function is dev and can be deployed to prod
**VC PASSED**
**VC FAILED**
Ongoing work to replace IssueCredential statemachine with IssueCredential Function
- [OJ-3228](https://govukverify.atlassian.net/browse/OJ-3228)
[OJ-3228]: https://govukverify.atlassian.net/browse/OJ-3228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3228: Deploy IssueCredential Function to prod

- infrastructure/template.yaml
Add 5xx canary alarms for check and issue credential
So that errors are caught by canary deployments
- [OJ-3336](https://govukverify.atlassian.net/browse/OJ-3336)
[OJ-3336]: https://govukverify.atlassian.net/browse/OJ-3336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3336: Add 5xx canary alarms for check and issue credential

- infrastructure/template.yaml
Added SubscriptionFilter to `IssueCredentialFunction` log group.
Fixed a C&P error in `IssueCredentialFunction5xxCanaryErrors` alarm.
IssueCredential logs were not showing in Splunk
- [OJ-3341](https://govukverify.atlassian.net/browse/OJ-3341)
[OJ-3341]: https://govukverify.atlassian.net/browse/OJ-3341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3341: Fix issue cred logs not showing in Splunk

- integration-tests/api-gateway/abandon/abandon-happy.test.ts
- integration-tests/api-gateway/audit.ts
- integration-tests/api-gateway/check/check-lambda-happy.test.ts
- integration-tests/api-gateway/e2e/e2e-happy-path.test.ts
- lambdas/common/src/util/audit.ts
- lambdas/common/tests/util/audit.test.ts
- Removed `client_id` from `sendAuditEvent()` function
The `clientId` in the session table is not the same thing as the `client_id` in the audit event. The former is the caller of our specific CRI, whereas the latter is the caller of One Login (ie, the RP). Leaving `client_id` unset allows the TxMA event processing logic to enrich the event with the RP client id from other events that correspond to the same user journey.
- OJ-3434
> OJ-3434 - Omit client_id in audit events
